### PR TITLE
Distance conversion GUI 

### LINKED ISSUE #814: Distance conversions
# Aim

- What is the objective of the Script
Use it to convert the distances from one unit to other .
Ex. cm to km or m to mm
# Details

- What the features will your script have
A simple GUI with conversion options for different units of measurement

### PR DESCRIPTION
**Pull request by tanvi355**
# Description

Added a unit converter for distance with GUI.

## Fixes #(issue_no)

Fixes #814 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by santushtisharma10 — APPROVED** [review]
@tanvi355 💯

**Comment by santushtisharma10** [comment]
@Kushal997-das

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
Remove the border of "from and to" and add these borders to select unit
image

**Review by Kushal997-das — APPROVED** [review]
LGTM 💯

**Comment by tanvi355** [comment]
> Remove the border of "from and to" and add these borders to select unit
> image

I can't figure out how to do it for OptionMenu...can you please help? Or should I just remove the border of "from" and "to"?

**Comment by kaustubhgupta** [comment]
> > Remove the border of "from and to" and add these borders to select unit
> > image
> 
> I can't figure out how to do it for OptionMenu...can you please help? Or should I just remove the border of "from" and "to"?

yes, removing the border is feasible instead of shifting/adding

**Review by kaustubhgupta — APPROVED** [review]
Clean UI, good CQ 💯, Keep improving!

**Comment by tanvi355** [comment]
If I have to update the screenshots , then I will have to delete the previous one in my forked repo and add new ones and then push them right?

**Comment by kaustubhgupta** [comment]
> If I have to update the screenshots , then I will have to delete the previous one in my forked repo and add new ones and then push them right?

You can replace those old screenshots with new ones with the same name and they will b updated

**Review by antrikshmisri — APPROVED** [review]
LGTM 💯

**Comment by tanvi355** [comment]
Updated the screenshots

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯

**Pull request merged**
