### PR TITLE
Password manager GUI

### LINKED ISSUE #694: Password manager GUI
# Aim
To provide a password manager application which can help user store passwords safely

# Details
User can manage records of all the passwords. Details like URL of website / Application name of which the password needs to be stored , username and password will be stored in a SQL database

### PR DESCRIPTION
**Pull request by Ayushjain2205**
# Description

Script added for Password Manager GUI. This lets the user enter and store passwords safely in a local SQL Database

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
Some suggestions:
- Create a mater password for the database and prompt to authenticate everytime user clicks on show-all. You need the SQLCipher module to read that database. The default SQLite3 module has no support for that.
- The alignment in showing passwords is not so good. Use some layouts to position them correctly.

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  Sure will work on these suggestions and get back

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 updates?

**Comment by Ayushjain2205** [comment]
Working on it will be done in a days time

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  I am not able to install pysqlcipher from the link given in the above issue. Can you please guide me how I can install it because I am unable to use it even after successful installation of it through pip

**Comment by kaustubhgupta** [comment]
Try this: https://github.com/Monogi/pysqlcipher3_install_win10

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 did you try this?

**Comment by kaustubhgupta** [comment]
https://charlesleifer.com/blog/sqlite-database-authorization-and-access-control-with-python/

you can do this also

**Comment by Ayushjain2205** [comment]
> Try this: https://github.com/Monogi/pysqlcipher3_install_win10

I tried this but I was not able to install it. I will go ahead with the new method you sent

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 updates?

**Comment by Ayushjain2205** [comment]
> Some suggestions:
> 
> * Create a master password for the database and prompt to authenticate every time user clicks on show-all. You need the SQLCipher module to read that database. The default SQLite3 module has no support for that.
> * The alignment in showing passwords is not so good. Use some layouts to position them correctly.

I have created the master password functionality. The user needs to add the master password as a command line argument and whenever the user clicks show all he needs to enter the password. 
Only on successful authentication all passwords will be shown.

**Review by kaustubhgupta — APPROVED** [review]
@Ayushjain2205 Good Job 💯 💯

**Review by santushtisharma10 — APPROVED** [review]
Nice @Ayushjain2205 💯💯

**Comment by kaustubhgupta** [comment]
@Kushal997-das

**Comment by kaustubhgupta** [comment]
@antrikshmisri

**Review by antrikshmisri — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]
LGTM...

**Pull request merged**
