### PR TITLE
Script to extract emails from a website content

### LINKED ISSUE #523: A python script to fetch all emails from a website
# Aim

- What is the objective of the Script
- This script fetches the content of a website and returns all the email ids provided in the website through printing them and storing them in a seperate text file of desired name.

# Details

- What the features will your script have
This is a CLI tool where you need to enter the target website and then you can type the name of the output text file and the python script will return all the emails provided in the website.

### PR DESCRIPTION
**Pull request by ankurg132**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #523 

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
- Script doesn't work as val will always be undefined
- Provide some spacing in-between different sections
- "Enter the file Name you want: " rewrite it as "Enter the file Name you want (without extension):"
- Handle the case when there is no email.

**Review by ankurg132 — COMMENTED** [review]
Resolved the following problems:
- Script will now work 
- Provided some spacing in-between different sections
- "Enter the file Name you want: " rewrote it as "Enter the file Name you want (without extension):"
- Handled the case when there is no email.
- Removed unnecessary comments

**Review by kaustubhgupta — APPROVED** [review]

**Comment by kaustubhgupta** [comment]
@santushtisharma10 @antrikshmisri

**Review by antrikshmisri — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]

**Comment by avinashkranjan** [comment]
@all-contributors please add @ankurg132 for code and documentation

**Pull request merged**
