### PR TITLE
SMS automation

### LINKED ISSUE #279: SMS Automation
# Aim

- The Aim is to send SMS (Short message service) to multiple people using python.

# Details

- It will be able to send message to multiple people by one script
- Scheduler will be there to send messages (greetings etc.) to send SMS at a particular time.

### PR DESCRIPTION
**Pull request by Amit366**
# Description

Script to send SMS to multiple people

## Fixes #279 

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by Amit366** [comment]
@santushtisharma10 please review it

**Comment by santushtisharma10** [comment]
@Amit366 your script is working, but there are certain runtime error that a user can run into like here user can send messages to only those number which are verified on their twilio account, geo permission error . So either add comments in your code or add in your readme file , telling user that before sending messages,the number to which they want to send message must be verified on their twilio account and also to enable geo permissions.

**Review by santushtisharma10 — CHANGES_REQUESTED** [review]
@Amit366 you may add setup instruction in your readme file. You can mention the instruction to avoid these error there

**Comment by Amit366** [comment]
@santushtisharma10 done.

**Review by santushtisharma10 — APPROVED** [review]
@Amit366 💯

**Comment by santushtisharma10** [comment]
@Kushal997-das

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
Please add a GIF to prove the working of the script as I have exhausted my Twilio credits. Make sure to hide personal details and phone number

**Comment by Amit366** [comment]
@kaustubhgupta I too have exhausted the credits😅😅

**Comment by Amit366** [comment]
It is already been reviewed by one of the mentors.

**Review by kaustubhgupta — APPROVED** [review]

**Comment by santushtisharma10** [comment]
@antrikshmisri

**Review by antrikshmisri — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
