### PR TITLE
added flipkart scraper for gssoc'23 contribution

### PR DESCRIPTION
**Pull request by paritoshtripathi935**
# Description
This pull request aims to add the Flipkart Scraper project to the Amazing Python Scripts repository. The project allows users to scrape product information from the Flipkart e-commerce platform.

## Type of change
 - New Addition to the Amazing-Python-Scripts
 
## Checklist:
 My code follows the style guidelines (Clean Code) of this project - 
 - I have performed a self-review of my own code
 - I have commented my code, particularly in hard-to-understand areas
 - I have created a helpful and easy-to-understand README.md
 - My documentation follows the [Template for README.md](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
-  I have created the requirements.txt file if needed.

# Project Metadata
## Category:
- Scrappers

### Description:
- The Flipkart Scraper is a Python script that allows users to extract product information from the Flipkart e-commerce platform. It scrapes data such as product name, price, description, and more. The script does not require any arguments to run.
- Stores the data in flipkart.db

### CODE REVIEW

**Comment by avinashkranjan** [comment]
Where is the script ?? @paritoshtripathi935

**Comment by paritoshtripathi935** [comment]
@avinashkranjan sorry , They were not pushed because of .git-ignore file , let me fix and push again

**Comment by paritoshtripathi935** [comment]
@avinashkranjan have a look again, added and tested it on local.

**Comment by paritoshtripathi935** [comment]
#1479
@avinashkranjan this is the issue number i have already added this in description of this pr and title.

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
