### PR TITLE
Added degrees of seperation

### LINKED ISSUE #715: Degrees of seperation
# Aim

- Implement a modified version of six degrees from Kevin Bacon game

# Details

- This script will find degrees of separation between any two actors by finding the shortest path by choosing a sequence of movies that connects them.

### PR DESCRIPTION
**Pull request by sandra9711**
# Description

Added degrees of separation finder game script

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x]  My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by santushtisharma10** [comment]
@sandra9711 your code is exactly same as this [code](https://www.reddit.com/r/learnpython/comments/g63ngv/degrees_of_separation_between_moviestars/).

**Comment by kaustubhgupta** [comment]
Hmm yet another case of plagiarism 😶

**Comment by antrikshmisri** [comment]
> Hmm yet another case of plagiarism 😶

I'll try to setup the github action for plagiarism tomorrow , till then ping PA about the situation.

**Comment by sandra9711** [comment]
@santushtisharma10 
This project was part of an online course and the first part (code and dataset ) was given in the question itself. I have done the searching algorithm part only.

**Comment by santushtisharma10** [comment]
@sandra9711 okay, but  if you take help from some code or from some website, so please mention it to avoid misunderstanding.

**Comment by sandra9711** [comment]
@santushtisharma10 
Sorry for the mistake. This was my first time making a PR.So, I was not aware of that.

**Pull request closed without merging**
