### PR TITLE
Cryptocurrency Wallet

### LINKED ISSUE #771: Cryptocurrency Wallet
# Aim
Cryptocurrency Wallet using Python and Cryptography Concepts

# Details

In this program, I will be building a program that can perform the whole process of mining a  block, generating private and public keys along with keeping tracks of its peers, and is capable of dynamically stabilizing the difficulty of the block according to the time requirements and can also transact the transaction and sign them digitally.

@avinashkranjan I am a GSSoC'21 participant and I think this is an interesting python project kindly allow me to work on this project.

### PR DESCRIPTION
**Pull request by Arnab11917676**
# Description
This is a simple Cryptocurrency wallet made with the help of python and its associate libraries and PubNub for the api calls. In this project it is shown how a cryptocurrency wallet keep track od the user transaction and this total project is build on the basis of Blockchain where the mining is happening and the time is dynamically adjusted with mean time of 4sec/ transaction speed. If sometime the transaction time is increased due to comparatively easy Proof Of Work (PoW) to agree to the consensus in the next transaction the complexity is increased by 1 zero(0) in front the Nonce. The program is build in such a way that it can simulate real life Blockchain ledger keeping by updating the ledger to each and every Node of the Network. In this program also a new instance of the current blockchain can be created and from that instance blocks can be mined and transactions can be made.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — COMMENTED** [review]
This is a full-fledged project! @antrikshmisri @santushtisharma10 Thoughts?

**Comment by Arnab11917676** [comment]
Sir, what do I do now?

**Comment by antrikshmisri** [comment]
@kaustubhgupta Agreed, @Arnab11917676 the project should have a small scope. This is a full fledged project

**Comment by kaustubhgupta** [comment]
@Arnab11917676 If you can reduce the functions of this project to some specific scripts only then we can give you 2-3 days for  that else we need to close this PR and issue

**Comment by Arnab11917676** [comment]
Okey sir this was a cryptocurrency wallet I don't want to reduce the functions. You can close the issue now..
Thank you sir

**Pull request closed without merging**
