### PR TITLE
 Creating-Emoji-Using-Python/README.md 

### PR DESCRIPTION
**Pull request by Ayush7614**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Ayush7614** [comment]
@avinashkranjan sir plss review it 
#179

**Comment by avinashkranjan** [comment]
@Ayush7614 Kindly Create a Issue for the Same

**Comment by Ayush7614** [comment]
@avinashkranjan sir plss review it i created a issue also #182

**Comment by Ayush7614** [comment]
@avinashkranjan sir #179 this is the pull request

**Comment by Ayush7614** [comment]
@avinashkranjan #182 this is issue

**Comment by Ayush7614** [comment]
@avinashkranjan sir plss review it and merged it

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
