### PR TITLE
Anime tracker

### LINKED ISSUE #165: Anime tracker
# Aim

- A script which checks for new episode release of a particular anime automatically

# Details

- It will accept a link to the anime from any anime website.
- Give alert if a new episode is released

### PR DESCRIPTION
**Pull request by pritamp17**
Created python script that gives anime information, total episodes, rating and Tags.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Kindly Add test Screenshots and a Readme Along with the Script

**Comment by pritamp17** [comment]
@avinashkranjan sir I have added readme and screenshot.

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯

**Comment by avinashkranjan** [comment]
@all-contributors please add @pritamp17  for code and documentation

**Pull request merged**
