### PR TITLE
Video to audio converter

### LINKED ISSUE #429: Video to Audio converter
# Aim

- A simple automation script to convert any type of video to audio.

#GSSOC'21

### PR DESCRIPTION
**Pull request by smriti1313**
# Description

A python script to convert video to audio.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have performed a self-review of my own code
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by kaustubhgupta — APPROVED** [review]

**Comment by kaustubhgupta** [comment]
@santushtisharma10 @tamanna-verma @antrikshmisri

**Review by santushtisharma10 — APPROVED** [review]

**Review by antrikshmisri — APPROVED** [review]

**Comment by smriti1313** [comment]
Hi, since video-to-audio converter PR was not closed and then now I edited the repo, I guess new changes are reflected here too. 
The commit `beefe94`  has my caesar-cipher update too. What shall i do now?

**Comment by kaustubhgupta** [comment]
> Hi, since video-to-audio converter PR was not closed and then now I edited the repo, I guess new changes are reflected here too.
> The commit `beefe94` has my caesar-cipher update too. What shall i do now?

Delete the commit from this PR. That's why we instruct participate to create seperate branches for different features as I can see this PR was made from the master branch. Try to delete the commit or delete the extra files from here and create a seperate branche for next script

**Comment by antrikshmisri** [comment]
> Hi, since video-to-audio converter PR was not closed and then now I edited the repo, I guess new changes are reflected here too.
> The commit `beefe94` has my caesar-cipher update too. What shall i do now?

If you feel stuck [this](https://stackoverflow.com/questions/36265506/git-delete-a-commit-from-pull-request) thread might help.

**Comment by smriti1313** [comment]
> 
> 
> > Hi, since video-to-audio converter PR was not closed and then now I edited the repo, I guess new changes are reflected here too.
> > The commit `beefe94` has my caesar-cipher update too. What shall i do now?
> 
> Delete the commit from this PR. That's why we instruct participants to create separate branches for different features as I can see this PR was made from the master branch. Try to delete the commit or delete the extra files from here and create a separate branch for the next script

Hi, I have reverted the commit `beefe94`. Is everything fine now?

**Comment by kaustubhgupta** [comment]
> > > Hi, since video-to-audio converter PR was not closed and then now I edited the repo, I guess new changes are reflected here too.
> > > The commit `beefe94` has my caesar-cipher update too. What shall i do now?
> > 
> > 
> > Delete the commit from this PR. That's why we instruct participants to create separate branches for different features as I can see this PR was made from the master branch. Try to delete the commit or delete the extra files from here and create a separate branch for the next script
> 
> Hi, I have reverted the commit `beefe94`. Is everything fine now?

Yes 👍🏼

**Review by avinashkranjan — APPROVED** [review]

**Comment by avinashkranjan** [comment]
@all-contributors please add @smriti1313 for code and documentation

**Pull request merged**
