### PR TITLE
Added New Script (WhatsApp-Auto-Messenger)

### PR DESCRIPTION
**Pull request by AnandD007**
Send and schedule a message in WhatsApp by only seven lines of Python Script.

# Description

Added New Script (WhatsApp-Auto-Messenger)

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by AnandD007** [comment]
### Changes remaining need to be done after pull request :
- I will add the README.md file
- I will add the requirements.txt file for libraries installation

**Comment by avinashkranjan** [comment]
Create an Issue for the PR. @AnandD007

**Comment by AnandD007** [comment]
Okay

**Review by avinashkranjan — APPROVED** [review]
LGTM

**Comment by avinashkranjan** [comment]
@all-contributors please add @AnandD007 for code

**Pull request merged**
