### PR TITLE
amazing python scripts: add website status checker

### LINKED ISSUE #320: website_status_checker script
# Details

- Added a script that takes a web address as an input and returns the status code of the web address

can you assign me this issue?  @avinashkranjan

### PR DESCRIPTION
**Pull request by hpnightowl**
# Description

This script will check the status of the web address which you will input

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [X] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [X] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Mention Status Code and their Meaning in the `README.md`

**Comment by hpnightowl** [comment]
ok sure

**Comment by hpnightowl** [comment]
pushed

**Comment by avinashkranjan** [comment]
@all-contributors please add @hpnightowl for code and documentation

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
