### PR TITLE
MAD LIBS GAME

### PR DESCRIPTION
**Pull request by Mrinal81**
@santushtisharma10 @kaustubhgupta  I made a PR of MAD LIBS GAME ..........

THIS PR BELONGS TO ISSUE 

Fixes: #1005 .........

Please have a look on it like is it OK or i have to change something.........

### CODE REVIEW

**Review by kaustubhgupta — COMMENTED** [review]
What is this? You are taking 3 inputs and just printing them?

We cannot accept this script. Thoughts? @antrikshmisri @santushtisharma10

**Comment by santushtisharma10** [comment]
Agreed @kaustubhgupta.

**Comment by kaustubhgupta** [comment]
> @Mrinal81 but if you can add features like
> 
> * add multiple stories and allow user to choose the story by title
> * make it a gui application (only a suggestion)
> 
> then i guess it may be acceptable
> What do you say @kaustubhgupta @antrikshmisri ?

Yes, this can be done. I think multiple stories selection is good and we can avoid GUI for this considering the issue is level 1

**Comment by Mrinal81** [comment]
@santushtisharma10 @kaustubhgupta ok

**Comment by kaustubhgupta** [comment]
@Mrinal81 updates on this?

**Comment by kaustubhgupta** [comment]
@Mrinal81?

**Comment by kaustubhgupta** [comment]
PR closed due to inactivity from participant side

**Pull request closed without merging**
