### PR TITLE
Translator gui

### LINKED ISSUE #503: Translator with gui
# Aim

To build a language translator using python

# Details

This script will allow users to translate between languages of their choice. This will be achieved using the help of the googletrans python package

### PR DESCRIPTION
**Pull request by Ayushjain2205**
# Description

Python script for Translator with GUI added

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

_Please delete options that are not relevant._
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by antrikshmisri** [comment]
@kaustubhgupta @santushtisharma10 UI looks good , can you guys confirm if the translation works. I can't get the `googletrans` dependency on my local machine.

**Review by kaustubhgupta — APPROVED** [review]
Pretty Good Implementation 💯 💯 

image

**Comment by santushtisharma10** [comment]
💯 🚀

**Review by santushtisharma10 — APPROVED** [review]

**Review by antrikshmisri — APPROVED** [review]
LGTM ⚡ ⚡

**Review by avinashkranjan — APPROVED** [review]
LGTM

**Pull request merged**
