### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by STARK-yv**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by avinashkranjan** [comment]
@STARK-yv What is this?

**Comment by STARK-yv** [comment]
> @STARK-yv What is this?
> Cloning someone else's repo and pushing it to my repo..is it supposed to be any kind of your contribution?

It's just an voice assistant program in python.

**Comment by STARK-yv** [comment]
> > @STARK-yv What is this?
> > Cloning someone else's repo and pushing it to my repo..is it supposed to be any kind of your contribution?
> 
> It's just an voice assistant program in python. 

It's not even completed yet but I'm trying and I saw this repository and tried to contribute a simple voice assistant project so that i can understand which things must me improved and can be changed, but dude.... Although your repository is nice but that doesn't mean you can be rude

**Comment by avinashkranjan** [comment]
> > > @STARK-yv What is this?
> > > Cloning someone else's repo and pushing it to my repo..is it supposed to be any kind of your contribution?
> > 
> > 
> > It's just an voice assistant program in python.
> 
> It's not even completed yet but I'm trying and I saw this repository and tried to contribute a simple voice assistant project so that i can understand which things must me improved and can be changed, but dude.... Although your repository is nice but that doesn't mean you can be rude

I'm not being rude, I'm telling you stop copying and pasting someone else's code it would take you no where and it would be worth nothing...Now you'd like to know how I know it's not your repo that's cause you have pushed `MIT License` along with your code which clearly states that it does not belong to you. Even if you copying and pasting at least hav a look at the files..

**Comment by STARK-yv** [comment]
> > > > @STARK-yv What is this?
> > > > Cloning someone else's repo and pushing it to my repo..is it supposed to be any kind of your contribution?
> > > 
> > > 
> > > It's just an voice assistant program in python.
> > 
> > It's not even completed yet but I'm trying and I saw this repository and tried to contribute a simple voice assistant project so that i can understand which things must me improved and can be changed, but dude.... Although your repository is nice but that doesn't mean you can be rude
> 
> I'm not being rude, I'm telling you stop copying and pasting someone else's code it would take you no where and it would be worth nothing...Now you'd like to know how I know it's not your repo that's cause you have pushed `MIT License` along with your code which clearly states that it does not belong to you. Even if you copying and pasting at least hav a look at the files..

Yes I added `MIT License` because my friend suggested me to add this in every repo that's why I added it

**Comment by avinashkranjan** [comment]
> > > > > @STARK-yv What is this?
> > > > > Cloning someone else's repo and pushing it to my repo..is it supposed to be any kind of your contribution?
> > > > 
> > > > 
> > > > It's just an voice assistant program in python.
> > > 
> > > 
> > > It's not even completed yet but I'm trying and I saw this repository and tried to contribute a simple voice assistant project so that i can understand which things must me improved and can be changed, but dude.... Although your repository is nice but that doesn't mean you can be rude
> > 
> > 
> > I'm not being rude, I'm telling you stop copying and pasting someone else's code it would take you no where and it would be worth nothing...Now you'd like to know how I know it's not your repo that's cause you have pushed `MIT License` along with your code which clearly states that it does not belong to you. Even if you copying and pasting at least hav a look at the files..
> 
> Yes I added `MIT License` because my friend suggested me to add this in every repo that's why I added it

It's not the License I'm Talking about it the name in the License 
Screenshot 2021-01-17 184250. 
Do you still have something to say about it... and you don't push License along with the PR..

**Comment by STARK-yv** [comment]
> > > > > > @STARK-yv What is this?
> > > > > > Cloning someone else's repo and pushing it to my repo..is it supposed to be any kind of your contribution?
> > > > > 
> > > > > 
> > > > > It's just an voice assistant program in python.
> > > > 
> > > > 
> > > > It's not even completed yet but I'm trying and I saw this repository and tried to contribute a simple voice assistant project so that i can understand which things must me improved and can be changed, but dude.... Although your repository is nice but that doesn't mean you can be rude
> > > 
> > > 
> > > I'm not being rude, I'm telling you stop copying and pasting someone else's code it would take you no where and it would be worth nothing...Now you'd like to know how I know it's not your repo that's cause you have pushed `MIT License` along with your code which clearly states that it does not belong to you. Even if you copying and pasting at least hav a look at the files..
> > 
> > Yes I added `MIT License` because my friend suggested me to add this in every repo that's why I added it
> 
> It's not the License I'm Talking about it the name in the License 
> Screenshot 2021-01-17 184250. 
> Do you still have something to say about it... and you don't push License along with the PR..
> 

I got your point
But i request you to check my JARVIS repo on my profile and believe me i was not aware of the license file I used to add it because my friend suggested it

**Comment by avinashkranjan** [comment]
> > > > > > > @STARK-yv What is this?
> > > > > > > Cloning someone else's repo and pushing it to my repo..is it supposed to be any kind of your contribution?
> > > > > > 
> > > > > > 
> > > > > > It's just an voice assistant program in python.
> > > > > 
> > > > > 
> > > > > It's not even completed yet but I'm trying and I saw this repository and tried to contribute a simple voice assistant project so that i can understand which things must me improved and can be changed, but dude.... Although your repository is nice but that doesn't mean you can be rude
> > > > 
> > > > 
> > > > I'm not being rude, I'm telling you stop copying and pasting someone else's code it would take you no where and it would be worth nothing...Now you'd like to know how I know it's not your repo that's cause you have pushed `MIT License` along with your code which clearly states that it does not belong to you. Even if you copying and pasting at least hav a look at the files..
> > > 
> > > 
> > > Yes I added `MIT License` because my friend suggested me to add this in every repo that's why I added it
> > 
> > 
> > It's not the License I'm Talking about it the name in the License
> > Screenshot 2021-01-17 184250.
> > Do you still have something to say about it... and you don't push License along with the PR..
> 
> I got your point
> But i request you to check my JARVIS repo on my profile and believe me i was not aware of the license file I used to add it because my friend suggested it

And Here https://github.com/Arbazkhan4712/JARVIS-Udemy-Code Found the Original Repo. You can even cloned the ReadMe with his stats..

**Comment by avinashkranjan** [comment]
Well @STARK-yv that doesn't solve anything..

**Comment by STARK-yv** [comment]
> Well @STARK-yv that doesn't solve anything..

Then run both the code, it might then....

**Pull request closed without merging**
