### PR TITLE
GST Calculator

### LINKED ISSUE #976: GST Claculator
# Aim

GST calculator GUI

# Details

By entering the original price and net price the script will calculate the GST percentage.

### PR DESCRIPTION
**Pull request by Amit366**
# Description

Added script GST calculation
## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [x] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: GST calculator

Folder: GST calculator

Requirements: none

Script: script.py

Arguments: none

Contributor: Amit366

Description: A GST calculator.

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
If I click find button one more time, the old result is still present, fix this: 

image

**Comment by Amit366** [comment]
@kaustubhgupta after every iteration click on clear

**Comment by Amit366** [comment]
Then it will be fine

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta after every iteration click on clear

I know the functioning of the **CLEAR button**. Every time you press find, it should not display the results in a continuous manner where previous results are still there but it should clear the previous text and then display a new one. **CLEAR Button** is to clear every field in the application.

**Comment by Amit366** [comment]
@kaustubhgupta please check now.

**Review by kaustubhgupta — APPROVED** [review]

**Review by santushtisharma10 — APPROVED** [review]

**Review by Kushal997-das — APPROVED** [review]
LGTM :+1:

**Review by antrikshmisri — APPROVED** [review]

**Review by kaustubhgupta — APPROVED** [review]

**Pull request merged**
