### PR TITLE
Guess_a_number.py

### LINKED ISSUE #2281: [Feat]: New project
### Is your feature request related to a problem? Please describe.

A new python project AI game where the AI tries to guess a number chosen by the player

### Describe the solution you'd like.

AI will make guesses and adjust its range of guesses based on the player's feedback

### Describe alternatives you've considered.

AI will make guesses and adjust its range of guesses based on the player's feedback

### Show us the magic with screenshots

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Shikhar9425**
# Description-A new python project AI game where the AI tries to guess a number chosen by the player. AI will make guesses and adjust its range of guesses based on the player's feedback

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [x] AI/ML
- [x] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [x] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [x] Others

Title: \<write script title here\>

Folder: \<type the folder name that contains your script\>

Requirements: \<type the name of text file containing the required to install python packages, type None if no file required\>

Script: \<Enter the name of the ``.py`` file (The main entry point of the program)\>

Arguments: \<enter any arguments that the script needs but `-` separeted like: h-c-m\>

Contributor: \<Enter your Github handle/username without url\>

Description: \<Enter a one line description that describes your script. Also, explain the arguments usage here\>

### CODE REVIEW

**Comment by Shikhar9425** [comment]
[readme.md](https://github.com/avinashkranjan/Amazing-Python-Scripts/files/12123223/readme.md)

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Add a `README.md` file

**Comment by Shikhar9425** [comment]
I have added the README.md file successfully . Please merge this pull request @avinashkranjan

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md

Please Follow this guidelines for the `README` file

**Comment by Shikhar9425** [comment]
@avinashkranjan I have updated the readme file

**Pull request merged**
