### PR TITLE
Create Age_Calculator.py   [GSSOC '23]

### LINKED ISSUE #1530: Want to create Age Calculator [GSSOC '23]
# Aim

- Simple Age calculator

# Details

- Just It will ask your date of birth then it will print your age in numbers so simple so easy to use!

### PR DESCRIPTION
**Pull request by Kalivarapubindusree**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

[Issue number](https://github.com/avinashkranjan/Amazing-Python-Scripts/issues/1530)

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [x] Calculators

### CODE REVIEW

**Comment by Kalivarapubindusree** [comment]
completed my task.

**Comment by avinashkranjan** [comment]
> completed my task.

Mention the Issue No, If Issue not created, Create an Issue First @Kalivarapubindusree

**Comment by Kalivarapubindusree** [comment]
My issue number #1529  calculate age

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Add a `README` File

**Comment by avinashkranjan** [comment]
Resolve the conflicts

**Comment by Kalivarapubindusree** [comment]
Yeah I have solved the conflicts please check it now pr @avinashkranjan

**Pull request closed without merging**
