### PR TITLE
Qr code Attendances 

### LINKED ISSUE #1016: GUI based QR_code_scanning
# Aim

- To take the Attendance of the students based on QR_codes.

# Details

- This project will be done in two steps. 

1. QR Generation 
2. QR Scanning

### QR Generation

Database of students will be provided in "Name - Roll number" format.
The QR code will store the values of "Name-Roll number" as UID
This script on run will generate the QR codes of all the students and save that as per their UID

### QR Scanning

Here the students will scan their QR codes.. and their attendance will be logged , separating the name and roll numbers along with the time of log.

The GUI will ask for the class details such as :
1. Couse name
2. course code
3. teachers names 
4. time of class 
5. Email, etc. 

Once the Qr Codes are scanned .. the Attendance sheet will be mailed to the mail ID provided in the GUI.

### PR DESCRIPTION
**Pull request by Yuvraj-kadale**
# Description

Adds the GUI based QR code Attendance system

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
- Delete all the images, upload them on imgur and then embed them here
- Shift all the code files from QR codes/src folder to QR_code_Excel_Attendace folder
- Add requirements.txt file for this.
- Add a script to update the database. It should not be manual work. Update the readme instruction too.
- Remove these files too: QR_code_Excel_Attendace/QR Codes/Student's QR/A - 0001.bmp

**Comment by Yuvraj-kadale** [comment]
> * Delete all the images, upload them on imgur and then embed them here
> * Shift all the code files from QR codes/src folder to QR_code_Excel_Attendace folder
> * Add requirements.txt file for this.
> * Add a script to update the database. It should not be manual work. Update the readme instruction too.
> * Remove these files too: QR_code_Excel_Attendace/QR Codes/Student's QR/A - 0001.bmp

Thanks @kaustubhgupta , will do this.
Could you please elaborate the 4th point?
I understand that I should update the database. But to make the process automated, I must fetch the information from some source. (Which source should it be?)

**Comment by kaustubhgupta** [comment]
> > * Delete all the images, upload them on imgur and then embed them here
> > * Shift all the code files from QR codes/src folder to QR_code_Excel_Attendace folder
> > * Add requirements.txt file for this.
> > * Add a script to update the database. It should not be manual work. Update the readme instruction too.
> > * Remove these files too: QR_code_Excel_Attendace/QR Codes/Student's QR/A - 0001.bmp
> 
> Thanks @kaustubhgupta , will do this.
> Could you please elaborate the 4th point?
> I understand that I should update the database. But to make the process automated, I must fetch the information from some source. (Which source should it be?)
> For the present script, the user is suppose to add/copy "student-roll number" in the `database.txt` file

What I mean is that create a script to add the student information in the database.

**Review by kaustubhgupta — COMMENTED** [review]
You have already submitted a PR on another repo: https://github.com/HarshCasper/Rotten-Scripts/pull/1049/files

Don't spam repositories

**Comment by Yuvraj-kadale** [comment]
@kaustubhgupta pardon me .. but submitting the same PR in two repositories isn't against the contributing guidelines.
letme know if i am wrong. 
I will be happy to close the PR open in another repo. and continue the work here. Since from the being I am contributing to this project.

**Comment by Yuvraj-kadale** [comment]
> > @kaustubhgupta pardon me .. but submitting the same PR in two repositories isn't against the contributing guidelines.
> > letme know if i am wrong.
> > I will be happy to close the PR open in another repo. and continue the work here. Since from the being I am contributing to this project.
> 
> This has been discussed with program organizers a long time ago: https://discord.com/channels/811724426965811210/811724426965811213/821722961378803762
> 
> Also, as I have closed the PR here, you can continue the contribution in that repo

Thanks wasn't aware of this. That makes sense. I will continue the contribution on that PR :)

**Pull request closed without merging**
