### PR TITLE
Sticky Notes

### LINKED ISSUE #582: Sticky notes GUI
# Aim

- A simple GUI based application in Python that helps you to create simple remember lists or sticky notes.

### PR DESCRIPTION
**Pull request by vikashkumar2020**
# Description

A simple GUI based application in Python that helps you to create simple remember lists or sticky notes.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
- I cannot add more notes
- The notes should be added in the GUI and not in terminal
- Option to delete the tasks done is not there
- As the name is sticky notes, change the background of GUI to yellow or something else
image

**Comment by vikashkumar2020** [comment]
Did the required changes please review it

**Review by kaustubhgupta — APPROVED** [review]
Dope Dude! 💯 💯 🥇 

image

**Review by antrikshmisri — APPROVED** [review]
LGTM 🔥

**Review by santushtisharma10 — APPROVED** [review]
@vikashkumar2020 💯 💯

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
