### PR TITLE
Make a banner image for repository

### LINKED ISSUE #131: Make a Banner Image for the Repository
# Aim

- Make a Banner Image for the Repository. The Banner Image can be simply the title of this Project with an awe-striking background. This Issue can be assigned to any number of participants but only one would be accepted as the Main Banner.

# Details

- You need to submit:

> - The Raw File of the Banner
> - A JPEG/PNG File of the Output

# Tools which can be Used

-  Adobe XD
- Figma
- Photoshop
- Illustrator

### PR DESCRIPTION
**Pull request by manastole03**
# Description

Created a banner image for the this repository.

## Fixes #131 

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
In this branch, there is a folder called the website. Navigate to that and replace this image with yours. Make sure to name it the same as named before (AmazingPyScripts.jpeg)

**Review by kaustubhgupta — APPROVED** [review]

**Review by Kushal997-das — APPROVED** [review]
LGTM 👍🏼

**Review by santushtisharma10 — APPROVED** [review]

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Kindly Push the RAW file too, So, It would be Easier for someone else to make some changes too

**Comment by manastole03** [comment]
Sure I will do that 🙂 @avinashkranjan

**Comment by kaustubhgupta** [comment]
@manastole03 You haven't uploaded the RAW image?

**Comment by manastole03** [comment]
I don't know how to add. 
Please guide me @kaustubhgupta

**Comment by kaustubhgupta** [comment]
Did you make this banner in any specific software right?

**Comment by manastole03** [comment]
Yes

**Comment by kaustubhgupta** [comment]
upload that project file in the repo. Put it under a new folder named: "Image RAW file"

**Comment by manastole03** [comment]
Okay 👍

**Comment by manastole03** [comment]
Done with the changes @kaustubhgupta

**Comment by kaustubhgupta** [comment]
> Done with the changes @kaustubhgupta

you upload another image. We want you to upload the project file. Like if you are working in Photoshop, then that project file

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
@manastole03 remove this image: Image RAW file.png

**Review by kaustubhgupta — APPROVED** [review]
@avinashkranjan 
As informed by @manastole03, This image was made in canvas and there are no associated project files/raw files. That's why we can approve this PR

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
