### PR TITLE
Image Base steganography script added

### LINKED ISSUE #599: Steganography
# Aim

- Python Script for Steganography

# Details

- Hiding text inside an Image and retrieving The text from an Image

### PR DESCRIPTION
**Pull request by dhriti987**
# Description

Added Image Based Steganography Script In Python. To Use This we have to install OpenCV module
## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — APPROVED** [review]
@dhriti987 Perfect Good Job! 💯 💯 
image

**Review by antrikshmisri — APPROVED** [review]

**Review by Kushal997-das — APPROVED** [review]
Good to me :)

**Review by santushtisharma10 — APPROVED** [review]
@dhriti987 💯 💯

**Comment by dhriti987** [comment]
Thanks

**Pull request merged**
