### PR TITLE
Ipl statistics gui

### LINKED ISSUE #840: IPL statistics GUI
# Aim

Let user choose what statistics of IPL they want to see and based on user choice web scrape it and display in a GUI

# Details

Statistics the user can choose include - Most runs, most wickets, most 4s, most 6s and about 10 more such statistics and can be chosen for every season (2008-2020)

### PR DESCRIPTION
**Pull request by Ayushjain2205**
# Description

GUI to see various statistics of the ipl 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  the data is getting printed in the formatted manner in the console but when it is getting added to the tkinter label it is getting little messed up... Any idea how I can fix this?
ipl_formatting bug

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta the data is getting printed in the formatted manner in the console but when it is getting added to the tkinter label it is getting little messed up... Any idea how I can fix this?
> ipl_formatting bug

This article should help: https://www.activestate.com/resources/quick-reads/how-to-position-widgets-in-tkinter/

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  I have fixed the issue, PR is ready for review
ipl_stats

**Review by kaustubhgupta — APPROVED** [review]
💯 💯

**Review by Kushal997-das — APPROVED** [review]
💯

**Review by santushtisharma10 — APPROVED** [review]

**Review by antrikshmisri — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯

**Pull request merged**
