### PR TITLE
automated_software_testing

### LINKED ISSUE #1986: [Script]: AUTOMATED Software testing using python.
### Aim

I want to add automated software testing script using python.
Can you please assign me this task under GSSOC'23 contribution @avi

### Details

Adding automatic software testing python script 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Kalivarapubindusree**
# Description
Automated python script is added.

## Fixes #1986 

#1986 

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)

## Project Metadata

" none "

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [x] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

### CODE REVIEW

**Comment by Kalivarapubindusree** [comment]
can you please review @avinashkranjan

**Comment by Kalivarapubindusree** [comment]
Ca you please review this pr @avinashkranjan

**Comment by Kalivarapubindusree** [comment]
Can you please merge this pr @avinashkranjan

**Comment by Kalivarapubindusree** [comment]
Can you please review this pr @avinashkranjan

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
