### PR TITLE
added a simple web browser made using python

### LINKED ISSUE #371: creation of web browser
# Aim

- What is the objective of the Script
- The objective of the script is to build a low functionality web browser

# Details
- What the features will your script have
- By this script we will be having some basic functionality of the web browser like searching the web

### PR DESCRIPTION
**Pull request by Sloth-Panda**
# Description
Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
It's a simple web browser made completely using python

## Fixes #371 

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.
Screenshot (154)
Screenshot (153)

### CODE REVIEW

**Comment by Sloth-Panda** [comment]
@avinashkranjan

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Add a README and have a look which lint base check is failing

**Comment by Sloth-Panda** [comment]
Okay, I will add the readme but I am not sure why the lint check is failing can you tell me why it can fail @avinashkranjan

**Comment by avinashkranjan** [comment]
> Okay, I will add the readme but I am not sure why the lint check is failing can you tell me why it can fail @avinashkranjan

Hav a look at this..
Screenshot 2021-02-23 013409

**Comment by Sloth-Panda** [comment]
@avinashkranjan 

I have added the readme, still the lint check is failing I am not getting why its showing undefined variable thing. I have removed empty lines from the code base too . so, take a look at it.

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Add a Issue for the Same.

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
