### PR TITLE
[GSSOC'23] Added Readme file for Webcam Image Capture

### LINKED ISSUE #1504: [ GSSOC '23 ] Adding README.md file for Webcam Image Capture Script
# Aim

- To add a comprehensive README.md file that provides clear instructions and documentation for the webcam image capture script.

Thank you for your attention to this matter.
@avinashkranjan

### PR DESCRIPTION
**Pull request by Abhishek-Rajput-81**
Hii @avinashkranjan  @Yashbhadiyadra, I've successfully added a README file for the Webcam Image Capture script.
#1504  My Issue Number

# Description

The README file provides an overview of the project, installation instructions, usage guidelines, and other relevant information. It aims to improve the project's documentation and make it easier for users to understand and use the code.

## Output
242835617-63d1190b-4335-4e34-879f-397a3cc41c63

## Type of change

- [x] This change requires a documentation update
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)

## Project Metadata

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [x] Others

Title: Added Readme file for Webcam Image Capture

Folder: Webcam-(imgcap)

Script: README.md

Contributor: Abhishek-Rajput-81

### CODE REVIEW

**Comment by Abhishek-Rajput-81** [comment]
@Yashbhadiyadra @Yashbhadiyadra

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan @Yashbhadiyadra 
@Yashbhadiyadra @avinashkranjan

**Comment by Abhishek-Rajput-81** [comment]
@Yashbhadiyadra @avinashkranjan

**Comment by Abhishek-Rajput-81** [comment]
@Yashbhadiyadra @Yashbhadiyadra

**Comment by Abhishek-Rajput-81** [comment]
@Yashbhadiyadra @avinashkranjan 
@avinashkranjan @Yashbhadiyadra

**Comment by Abhishek-Rajput-81** [comment]
@Yashbhadiyadra @Yashbhadiyadra

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
