### PR TITLE
add Bandwidth-Monitor script

### PR DESCRIPTION
**Pull request by adarshkushwah**
# Description

This script keeps track of the network data usage and notifies the user if it exceeds a defined limit.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have created a helpful and easy to understand `README.md`
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Resolve this error
vmware_4CHI2sv3rt

**Comment by adarshkushwah** [comment]
Please provide me the info on the below from your environment :

- Vnstat version
- Python3 version
- Python3-tk version (it should probably be similar to that of Python3)
- OS info

Will need to take the environment variables into consideration as well i guess, as I tested this on my system and on an another test virtual environment but it appears to be working fine.

**Review by avinashkranjan — APPROVED** [review]
LGTM..🚀 Works Now..

**Comment by avinashkranjan** [comment]
@all-contributors please add @adarshkushwah  for code and documentation

**Pull request merged**
