### PR TITLE
Added contact us files

### PR DESCRIPTION
**Pull request by fatma-sia27**
Hey I had made a contact us page . Please review this PR and let me know if any changes required.
Thank you 

Fixes: #812

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
Link the contact us page to the website files. The text for Contact us should appear here:

image

Clicking this text should open your webpage. Shift all the files related to contact_us in the website folder only in appropriate folders

**Comment by fatma-sia27** [comment]
> Link the contact us page to the website files. The text for Contact us should appear here:
> 
> image
> 
> Clicking this text should open your webpage. Shift all the files related to contact_us in the website folder only in appropriate folders

Hey @kaustubhgupta , inside website folder I should create a folder amd then shift all the files in that folder and then I have to make a fresh pull request. Right? Also should I push only website folder or all folder in gh page ???

**Comment by kaustubhgupta** [comment]
> > Link the contact us page to the website files. The text for Contact us should appear here:
> > image
> > Clicking this text should open your webpage. Shift all the files related to contact_us in the website folder only in appropriate folders
> 
> Hey @kaustubhgupta , inside website folder I should create a folder amd then shift all the files in that folder and then I have to make a fresh pull request. Right? Also should I push only website folder or all folder in gh page ???

You should integrate all your contact files in the website files. It should not be a separate folder. No, you don't need to make any new PR. Just make your changes locally and then:

`git add .` - to add files
`git status` - to check changed files
`git commit -m "<your commit  message"` 

And done, your latest changes will be automatically reflected here

**Comment by fatma-sia27** [comment]
Hey @kaustubhgupta , I had done the changes and commit . Please check whether it changes are reflecting on your side.
Thank you

**Comment by kaustubhgupta** [comment]
> Hey @kaustubhgupta , I had done the changes and commit . Please check whether the changes are reflecting on your side.
> Thank you

Nope, no changes are detected in this PR

**Comment by fatma-sia27** [comment]
> > Hey @kaustubhgupta , I had done the changes and commit . Please check whether the changes are reflecting on your side.
> > Thank you
> 
> Nope, no changes are detected in this PR

but I had done whatever you told to do.

**Comment by fatma-sia27** [comment]
Hey @kaustubhgupta  I did it again please check

**Comment by kaustubhgupta** [comment]
> Hey @kaustubhgupta I did it again please check

Yes they are visible now, I will review it in some time and get back to you for the feedback

**Comment by fatma-sia27** [comment]
> > Hey @kaustubhgupta I did it again please check
> 
> Yes they are visible now, I will review it in some time and get back to you for the feedback

okie

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
- Delete this contact_us folder:

image

- Add contact us hyperlink in the website.html also:

image

**Comment by fatma-sia27** [comment]
> * Delete this contact_us folder:
> 
> image
> 
> * Add contact us hyperlink in the website.html also:
> 
> image

Yeah done added contact us hyperlink in website.html
WhatsApp Image 2021-04-25 at 9 35 06 AM

**Comment by kaustubhgupta** [comment]
@fatma-sia27 you have not pushed your changes here, kindy do that

**Comment by fatma-sia27** [comment]
> @fatma-sia27 you have not pushed your changes here, kindy do that

@kaustubhgupta done

**Comment by kaustubhgupta** [comment]
> > @fatma-sia27 you have not pushed your changes here, kindy do that
> 
> @kaustubhgupta done

I don't know where you are pushing your changes, no commit is reflected in this PR. You can check it yourself.  None of the suggested changes are there

**Comment by fatma-sia27** [comment]
> > > Link the contact us page to the website files. The text for Contact us should appear here:
> > > image
> > > Clicking this text should open your webpage. Shift all the files related to contact_us in the website folder only in appropriate folders
> > 
> > 
> > Hey @kaustubhgupta , inside website folder I should create a folder amd then shift all the files in that folder and then I have to make a fresh pull request. Right? Also should I push only website folder or all folder in gh page ???
> 
> You should integrate all your contact files in the website files. It should not be a separate folder. No, you don't need to make any new PR. Just make your changes locally and then:
> 
> `git add .` - to add files
> `git status` - to check changed files
> `git commit -m "<your commit message>"`
> 
> And done, your latest changes will be automatically reflected here

@kaustubhgupta , I had done these steps . Still its not showing then what to do next?

**Comment by fatma-sia27** [comment]
@kaustubhgupta , I did it again please check.

**Review by kaustubhgupta — APPROVED** [review]

**Review by santushtisharma10 — APPROVED** [review]

**Review by antrikshmisri — APPROVED** [review]

**Comment by fatma-sia27** [comment]
@kaustubhgupta What will be the next step?

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta What will be the next step?

The PR will be merged by PA soon and you will get points on the leaderboard!

**Comment by fatma-sia27** [comment]
> > @kaustubhgupta What will be the next step?
> 
> The PR will be merged by PA soon and you will get points on the leaderboard!

Okay Thank you for your continuous support and guidance.

**Comment by kaustubhgupta** [comment]
> > > @kaustubhgupta What will be the next step?
> > 
> > 
> > The PR will be merged by PA soon and you will get points on the leaderboard!
> 
> Okay Thank you for your continuous support and guidance.

No problem, I appreciate your patience and applying the feedbacks as suggested 😀

**Comment by fatma-sia27** [comment]
@kaustubhgupta when will this PR will be merged?

**Pull request merged**
