### PR TITLE
Paint Application GUI

### LINKED ISSUE #685: Paint Application
# Aim

To make a mini version of MS paint using python GUI

# Details

User can draw on a canvas, change brush size and brush colour

### PR DESCRIPTION
**Pull request by Ayushjain2205**
# Description

Paint application GUI made using python. Provides functionality like drawing, saving file , using different colors and sizes of brushes

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  The application is working successfully on my machine, but here the check is failing and giving some error. Can you please tell me how do I need to proceed.

**Comment by antrikshmisri** [comment]
> @kaustubhgupta The application is working successfully on my machine, but here the check is failing and giving some error. Can you please tell me how do I need to proceed.

@Ayushjain2205 You have a lot of undefined variables you can check the logs [here](https://github.com/avinashkranjan/Amazing-Python-Scripts/runs/2160897442#step:4:76)

**Comment by Ayushjain2205** [comment]
@antrikshmisri This is a similar issue I found - [https://stackoverflow.com/questions/58650783/errors-faced-when-using-pyqt](https://stackoverflow.com/questions/58650783/errors-faced-when-using-pyqt)

It says that it is a problem with the linter which is not able to detect dynamic Pyqt5 modules and is labelling them as undefined variables

**The application is working perfectly** but the linter is giving this error

So how do I go about this ?

**Comment by antrikshmisri** [comment]
@Ayushjain2205 Yup I don't think this linter has support for dynamic modules.@kaustubhgupta @santushtisharma10 What do you guys think? Should change pylint settings accordingly?

**Comment by kaustubhgupta** [comment]
> @Ayushjain2205 Yup I don't think this linter has support for dynamic modules.@kaustubhgupta @santushtisharma10 What do you guys think? Should change pylint settings accordingly?

Pylint settings can't be changed for one case. @Ayushjain2205 I would suggest, instead of importing all (*), import only the required elements from the modules. Example: 
```python
from PyQt5.QtGui import QAction
```

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  I tried what you said but that also doesnt solve the problem

Capture

Any other suggestions to solve this issue?

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta I tried what you said but that also doesnt solve the problem
> 
> Capture
> 
> Any other suggestions to solve this issue?

Hmm, give me time till tomorrow morning, will get some ideas for this

**Comment by Ayushjain2205** [comment]
@kaustubhgupta Any ideas to proceed with this issue?

**Review by kaustubhgupta — APPROVED** [review]
@Ayushjain2205  Your application works perfectly. The pylint needs to be configured for the PyQT exceptions. Therefore, I am approving this PR.

**Comment by kaustubhgupta** [comment]
@santushtisharma10 @Kushal997-das The test is failing due this: https://stackoverflow.com/questions/58650783/errors-faced-when-using-pyqt and https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/695#issuecomment-804326317

Therefore, we need to ping PA to add PyQt to exceptions. For now, we can approve this PR after you suggest changes (if needed)

**Comment by santushtisharma10** [comment]
@Ayushjain2205 you have copied from [here](https://www.geeksforgeeks.org/pyqt5-create-paint-application/).  You have just removed some comments from the original code

**Comment by Ayushjain2205** [comment]
@santushtisharma10 I have referred to [this youtube video](https://www.youtube.com/watch?v=qEgyGyVA1ZQ&t=1285s) and when I was getting linting errors I refered to [this article](https://www.geeksforgeeks.org/pyqt5-create-paint-application/)

I have written all the code myself after understanding each and every line and I know what is happening in each and every line

**Comment by santushtisharma10** [comment]
@Ayushjain2205 all the variable name, values and even the function name are exactly same.

**Comment by Ayushjain2205** [comment]
@santushtisharma10 As this was the first time I was learning/using PyQt5 I have just coded along understanding how things are happening and what is happening.
I didnt realise it that time that I can change values just so that it doesnt appear as plagiarism 
I can change the code or even add more functionality to proove that this is not just blind copy paste but I have spent time and effort in learning and implementing this

**Comment by santushtisharma10** [comment]
> @santushtisharma10 As this was the first time I was learning/using PyQt5 I have just coded along understanding how things are happening and what is happening.
> I didnt realise it that time that I can change values just so that it doesnt appear as plagiarism
> I can change the code or even add more functionality to proove that this is not just blind copy paste but I have spent time and effort in learning and implementing this

@Ayushjain2205 okay, add a few more functionality

**Comment by Ayushjain2205** [comment]
@santushtisharma10 I have added the following functionalities 

1.  Change canvas color 
2.  Change brush style

canvas_color

brush_style

**Review by santushtisharma10 — APPROVED** [review]
LGTM

**Comment by santushtisharma10** [comment]
@Kushal997-das @kaustubhgupta

**Review by Kushal997-das — APPROVED** [review]
LGTM 💯

**Review by antrikshmisri — APPROVED** [review]

**Review by kaustubhgupta — APPROVED** [review]
@Ayushjain2205 Good Job 💯

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
