### PR TITLE
Modified the website(gh-pages branch)

### PR DESCRIPTION
**Pull request by SurbhiRathi23**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

-  Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

-  Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
-  Modification in Amazing-Python-Scripts website
-  Modified home.html and script.html

## Checklist:

-  My code follows the style guidelines(Clean Code) of this project
-  I have performed a self-review of my own code
-  I have commented my code, particularly in hard-to-understand areas
-  I have created a helpful and easy to understand `README.md`
-  My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- My changes generate no new warnings
- I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by SurbhiRathi23** [comment]
@kaustubhgupta  I can remove the minor space of background from top to navbar, but it was looking fine thats why I didn't removed it.

Search bar was not working when I get this issue, and It can be a new issue as it is a good enough work through javascript.

In this issue, I wanted to improve the design, look , and errors of the website. So, that's why I did only that. I didn't worked on search bar.

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta I can remove the minor space of background from top to navbar, but it was looking fine thats why I didn't removed it.
> 
> Search bar was not working when I get this issue, and It can be a new issue as it is a good enough work through javascript.
> 
> In this issue, I wanted to improve the design, look , and errors of the website. So, that's why I did only that. I didn't worked on search bar.

You can remove the space of the background from the top to the navbar. For the search bar, we will create another issue and then you can claim it if you wish to work on that

**Comment by kaustubhgupta** [comment]
@SurbhiRathi23 Also, as @kagritu has made the PR of the contributor's list:
image
I think @SurbhiRathi23 you should remove the changes of home.html as @kagritu has updated all the contributor's names with the exact image. If you wish, you can also remove the changes of home.css.

**Comment by SurbhiRathi23** [comment]
> @SurbhiRathi23 Also, as @kagritu has made the PR of the contributor's list:
> image
> I think @SurbhiRathi23 you should remove the changes of home.html as @kagritu has updated all the contributor's names with the exact image. If you wish, you can also remove the changes of home.css.

Okay. I will remove it.

**Comment by SurbhiRathi23** [comment]
@kaustubhgupta  I have made the changes you wanted me to do. Also, I have added some more styles.
You can review them. 
These are the changes I made -
- removed the styles of **contributors list** in **home.html**
- made background image of home.html responsive
- updated navbar and toggler

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
Perfect

**Review by kaustubhgupta — APPROVED** [review]

**Review by kaustubhgupta — APPROVED** [review]

**Review by antrikshmisri — APPROVED** [review]

**Review by santushtisharma10 — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
