### PR TITLE
Add linear search visualizer

### LINKED ISSUE #933: Linear search visualizer
# Aim

To create a GUI for linear search visualization.

### PR DESCRIPTION
**Pull request by tanvi355**
# Description

Add a visualizer for linear search algorithm.

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirements``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [x] Others

Title: Linear Search Visualizer

Folder: Linear Search Visualizer

Requirements: none

Script: script.py

Arguments: none

Contributor: tanvi355

Description: A GUI that allows you to see the linear search in action.

### CODE REVIEW

**Review by kaustubhgupta — APPROVED** [review]
💯

**Review by santushtisharma10 — CHANGES_REQUESTED** [review]
@tanvi355  looks good, just add a requirements.txt file

**Comment by kaustubhgupta** [comment]
> @tanvi355 looks good, just add a requirements.txt file

Actually tkinter is preinstalled, so we don't need requirements file for this :)

**Review by santushtisharma10 — APPROVED** [review]

**Review by Kushal997-das — APPROVED** [review]
LGTM 💯

**Review by antrikshmisri — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
