### PR TITLE
Last

### LINKED ISSUE #356: Last Access
# Aim

-list files in a directory and print when was the last time file was accessed.

# Details

- it will use os and time module.

### PR DESCRIPTION
**Pull request by Bug-007**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #356 

Replace #356 with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Bug-007** [comment]
Please review it.

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Don't Change anything in `Template for README.md`

**Comment by Bug-007** [comment]
I have fixed my accidental delete . Please review it.

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯

**Pull request merged**
