### PR TITLE
Added files for pwned or not

### LINKED ISSUE #931: Pawned or not?
**Describe the solution you'd like**
This script will let you check whether your password has been hacked or not by using https://haveibeenpwned.com/ database

I am a GSSOC21 Participant @avinashkranjan kindly assign me the same

### PR DESCRIPTION
**Pull request by RohiniRG**
# Description

The python script helps users to know if their passwords were ever part of a data breach, and thus helping them stay aware and change their passwords accordingly

## Fixes #931 

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

## Project Metadata
If there is no-file/nothing to fill the below fields with, then type: none`

`Example:` If no requirements.txt needed/present then type in `Requirments` none => `Requirments: none`
 
Category:
 
- [ ]  Calculators
- [ ]  AI/ML
- [x]  Scrappers
- [ ]  Social_Media
- [ ]  PDF
- [ ]  Image_Processing
- [ ]  Video_Processing
- [ ]  Games
- [ ]  Networking
- [ ]  OS_Utilities
- [ ]  Automation
- [x]  Cryptography
- [ ]  Computer_Vision
- [ ]  Fun
- [ ]  Others
 
Title: Pwned or not
 
Folder: Pwned_or_not_GUI
 
Requirements: requirements.txt
 
Script: pwned_passwords_GUI.py
 
Arguments: none
 
Contributor: RohiniRG 
 
Description: The python script helps users to know if their passwords were ever part of a data breach, and thus helping them stay aware and change their passwords accordingly. This information will be presented to users in a user-friendly GUI.

### CODE REVIEW

**Comment by santushtisharma10** [comment]
@RohiniRG your code is working fine, just add a button to hide/show password.

**Comment by RohiniRG** [comment]
> @RohiniRG your code is working fine, just add a button to hide/show password.

@santushtisharma10 I'm not really getting how to do this, although I tried it. Could you please provide a reference or alternative as to how to do this?

**Comment by RohiniRG** [comment]
@santushtisharma10 @kaustubhgupta I figured out the hide/show password. Please let me know if the changes are fine.

**Review by kaustubhgupta — APPROVED** [review]
💯

**Review by santushtisharma10 — APPROVED** [review]
@RohiniRG 💯 💯

**Review by antrikshmisri — APPROVED** [review]

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
@RohiniRG  Update the PR template with project metadata. Look at this PR for reference: https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/1002

**Comment by RohiniRG** [comment]
@kaustubhgupta please have a look. I made the changes.

**Review by kaustubhgupta — APPROVED** [review]

**Pull request merged**
