### PR TITLE
Saves file into mp3 format as well( answer to #108 )

### PR DESCRIPTION
**Pull request by Mr-Mishraji**
# Description

fixed the code so that it can save pdf file into mp3 file of the same name as pdf and the same directory where pdf file is . one more library added (gTTS).

## Fixes #(108)

Replace `108` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by avinashkranjan** [comment]
@Mr-Mishraji Please create a Issue for the Same..

**Comment by avinashkranjan** [comment]
Ohh Great..Thanks For Contributing..

**Comment by Mr-Mishraji** [comment]
> @Mr-Mishraji Please create a Issue for the Same..

ohk

**Review by avinashkranjan — APPROVED** [review]
LGTM..🚀

**Comment by Mr-Mishraji** [comment]
> LGTM..🚀

still  I have to create issue

**Comment by avinashkranjan** [comment]
> > LGTM..🚀
> 
> still I have to create issue
No..No It's alright...

@all-contributors please add @Mr-Mishraji  for code

**Pull request merged**
