### PR TITLE
Crypto price tracker GUI

### LINKED ISSUE #1124: Cryptocurrency price checker GUI (web scraping)
# Aim

To display live top cryptocurrency in a GUI

# Details

Web scrape this data from coinmarketcap.com or other such websites

### PR DESCRIPTION
**Pull request by Ayushjain2205**
# Description

This scripts shows top-100 cryptocurrency prices and other statistics related to them in a GUI , scraped from cointracker.io

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [x] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: Cryptocurrency Price Checker

Folder: Crypto-price-checker

Requirements: requirements.txt

Script: crypto.py

Arguments: none

Contributor: Ayushjain2205

Description: This scripts shows top-100 cryptocurrency prices and other statistics related to them in a GUI

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
The files got duplicated. Now you have two folders Crypto price checker and Crypto price dashboard. FIx this. Also, in the script, mak this change:

`driver_path = input('Enter chrome driver path: ')`

**Comment by Ayushjain2205** [comment]
@kaustubhgupta changes made

**Review by kaustubhgupta — APPROVED** [review]
nice 👍🏼 💯

**Review by santushtisharma10 — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]
LGTM..🚩

**Pull request merged**
