### PR TITLE
Added Sky Detection

### LINKED ISSUE #2324: [Script]: Air Object Detector
### Aim

Hello @avinashkranjan ,
Here is a project which detect the Air objects like Aeroplane, Birds, etc.
This helps Shipping and Aerospace Companies.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### Soon will raise a PR 👍🏻

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
# Description

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] New Script
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [x] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [x] Detection
- [ ] Others

Title: \<write script title here\>

Folder: AirObject

Requirements: cv2

Script: air.py

Contributor: SyedImtiyaz-1

### CODE REVIEW

**Comment by SyedImtiyaz-1** [comment]
Hello @avinashkranjan ,kindly review this.

**Comment by SyedImtiyaz-1** [comment]
@avinashkranjan ,
Please review this.

**Comment by SyedImtiyaz-1** [comment]
@avinashkranjan Please check this.

**Comment by SyedImtiyaz-1** [comment]
@avinashkranjan Please review this.

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Add a `README.md` file

**Comment by SyedImtiyaz-1** [comment]
@avinashkranjan , I have added the README.md

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md

Please Follow this guidelines for the `README` file

**Review by avinashkranjan — APPROVED** [review]

**Comment by SyedImtiyaz-1** [comment]
@avinashkranjan Thanks. 👍🏻

**Pull request merged**
