### PR TITLE
Stopwatch GUI

### LINKED ISSUE #741: Stopwatch GUI
# Aim
I would like to work create a  stopwatch GUI

# Details

I will create a stopwatch GUI  with tkinter , it will have a start /stop button 

Pls assign me this issue

### PR DESCRIPTION
**Pull request by aishwaryachand**
# Description

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [X] Yes
## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
Add a pause and resume button too so that one can take a break.
- Pressing pause will hold the time
- Resume will start the timer from that time

**Comment by kaustubhgupta** [comment]
@aishwaryachand updates on this?

**Comment by aishwaryachand** [comment]
> @aishwaryachand updates on this?
will make a PR today once done...actually started to work on it a bit late as I was stuck with an issue.

**Comment by kaustubhgupta** [comment]
> > @aishwaryachand updates on this?
> > will make a PR today once done...actually started to work on it a bit late as I was stuck with an issue.

Try to complete it today itself

**Comment by aishwaryachand** [comment]
added pause button to pause to stopwatch, the start button will resume (if the stopwatch is paused)  and reset button for resetting the stopwatch. Kindly review

**Review by kaustubhgupta — APPROVED** [review]
@aishwaryachand Good job 💯

**Review by santushtisharma10 — APPROVED** [review]
@aishwaryachand 💯 💯

**Comment by santushtisharma10** [comment]
@antrikshmisri

**Review by antrikshmisri — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
