### PR TITLE
Solved some problems

### LINKED ISSUE #131: Make a Banner Image for the Repository
# Aim

- Make a Banner Image for the Repository. The Banner Image can be simply the title of this Project with an awe-striking background. This Issue can be assigned to any number of participants but only one would be accepted as the Main Banner.

# Details

- You need to submit:

> - The Raw File of the Banner
> - A JPEG/PNG File of the Output

# Tools which can be Used

-  Adobe XD
- Figma
- Photoshop
- Illustrator

### PR DESCRIPTION
**Pull request by manastole03**
# Description

Fixing some small problems.

## Fixes #131 

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
@manastole03 nope, nope, your last PR had no issues and you don't need to solve any issues

**Comment by manastole03** [comment]
So now what I have to do ? @kaustubhgupta

**Comment by kaustubhgupta** [comment]
> So now what I have to do ? @kaustubhgupta

Nothing, your last pr will be reviewed by other mentors and then finally merged by PA

**Comment by manastole03** [comment]
Okay 👍

**Pull request closed without merging**
