### PR TITLE
GUI E-Mail Sender

### LINKED ISSUE #992: GUI Email Sender Application
# Aim
This is an e-mail sending GUI application.
# Details
In this application, I will be building a python based GUI application that will be able to send E-mail.

### PR DESCRIPTION
**Pull request by Arnab11917676**
# Description

This is a GUI Email Sender build using Tkinter and Smtplib. We can send emails from our Gmail account to other e-mail accounts.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Arnab11917676** [comment]
@santushtisharma10  please have a look...

**Comment by santushtisharma10** [comment]
@Arnab11917676 your code is quite similar to this [code](https://github.com/arka-nitd/send-email-gui/blob/master/emailapp.py).
@kaustubhgupta @antrikshmisri what are your thoughts?

**Comment by Arnab11917676** [comment]
Please send a email using that code and try mine...

**Comment by antrikshmisri** [comment]
> @Arnab11917676 your code is quite similar to this [code](https://github.com/arka-nitd/send-email-gui/blob/master/emailapp.py).
> @kaustubhgupta @antrikshmisri what are your thoughts?

Just changed some values, rest it is the same

**Review by kaustubhgupta — COMMENTED** [review]
The code is exactly the same as mentioned by other mentors. As you said, I tried sending mail via your code and as I was expecting, the authentication error because this is insecure way of sending mails. Hence this issue and PR are unassigned.

**Comment by Amit366** [comment]
@kaustubhgupta can I work on this??

**Pull request closed without merging**
