### PR TITLE
Added contour detection

### LINKED ISSUE #611: Contour/Shape Detection
# Aim

- How to detect shapes of objects by finding their contours.

# Details

- Contours are basically outline that bound the shape or form of an object. So we will be detecting multiple shapes and how many corners points each shape has along with its area .

### PR DESCRIPTION
**Pull request by mehabhalodiya**
# Description

Contours can be explained simply as a curve joining all the continuous points (along the boundary), having same color or intensity. The contours are a useful tool for shape analysis and object detection and recognition.

- For better accuracy, use binary images. So before finding contours, apply threshold or canny edge detection.

### About: Contour Approximation Method

I have used this method in **getContours()** function.
What does it denote actually?

We know that contours are the boundaries of a shape with same intensity. It stores the (x,y) coordinates of the boundary of a shape. But does it store all the coordinates ? That is specified by this contour approximation method.

If you pass cv.CHAIN_APPROX_NONE, all the boundary points are stored. But actually do we need all the points? For eg, you found the contour of a straight line. Do you need all the points on the line to represent that line? No, we need just two end points of that line. This is what cv.CHAIN_APPROX_SIMPLE does. It removes all redundant points and compresses the contour, thereby saving memory.

contour

Note: In this script, I have used cv2.CHAIN_APPROX_NONE.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
@mehabhalodiya Code works fine, just add the readme. 💯

**Comment by mehabhalodiya** [comment]
@kaustubhgupta @antrikshmisri @santushtisharma10 
Kindly review this.

**Review by santushtisharma10 — CHANGES_REQUESTED** [review]
`cap.release()`
`cv2.destroyAllWindows()`
@mehabhalodiya Add these at the end of your code

**Review by santushtisharma10 — APPROVED** [review]
LGTM  💯

**Review by kaustubhgupta — APPROVED** [review]
💯 💯

**Review by antrikshmisri — APPROVED** [review]
LGTM 👍🏻

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
