### PR TITLE
Social Media Links Code

### LINKED ISSUE #151: Script to scrap Social Media Pages of Websites
# Objective

- Create a Script that can analyze the Social Media Links on a Website and generate results. You can check for popular Social Media Links and generate them as a result. Integrate an option to also pick a CSV file of Websites to scrap their data together and store in a CSV.

### PR DESCRIPTION
**Pull request by twilight-warlock**
# Description

The issue "Script to scrap Social Media Pages of Websites" has been fixed by a python script with required code.
The code provides a menu driven program which asks if the user wants social media links of a single website or a csv file with multiple website links. A trial csv file is present in the PR as test input file followed by an output file which stores the links after scraping from their respective sites.

Dependencies:- 
- requests

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?
- Yes

## Type of change
- New feature (non-breaking change which adds functionality)

## Checklist:

- My code follows the style guidelines(Clean Code) of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- My changes generate no new warnings

### CODE REVIEW

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Add a README file..rest LGTM @twilight-warlock

**Comment by twilight-warlock** [comment]
Any specific format for the same? @avinashkranjan

**Comment by avinashkranjan** [comment]
> Any specific format for the same? @avinashkranjan

Yes,, Follow this [Template for README](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)

**Comment by twilight-warlock** [comment]
Completed requested changes. @avinashkranjan

**Comment by twilight-warlock** [comment]
Is there anything left or LGTM? @avinashkranjan

**Review by avinashkranjan — APPROVED** [review]
LGTM..🚀

**Comment by avinashkranjan** [comment]
@all-contributors please add @twilight-warlock  for code and documentation

**Pull request merged**
