### PR TITLE
Dictionary GUI

### LINKED ISSUE #722: Dictionary GUI
# Aim

To provide a dictionary GUI in which user can search for words and can find meanings and synonyms as the result

# Details

The user is required to enter the word in a searchbox and after fetching the result the meaning and synonym of the word will get displayed

### PR DESCRIPTION
**Pull request by Ayushjain2205**
# Description

Dictionary script added to let users search meaning of words through a GUI

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — APPROVED** [review]
@Ayushjain2205 💯

**Comment by kaustubhgupta** [comment]
@Kushal997-das

**Review by santushtisharma10 — APPROVED** [review]
@Ayushjain2205 💯

**Review by Kushal997-das — APPROVED** [review]
LGTM 💯

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
