### PR TITLE
Added the gui program for FLAMES game

### PR DESCRIPTION
**Pull request by jayaganeshkumar**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Added the gui program for flames game. Python is the dependency.

## Fixes #(#94 )

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [X] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [X] Added new feature for the project

## Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by jayaganeshkumar** [comment]
@avinashkranjan  Done! Check it and accept it, merge it and label it with "hacktoberfest-accepted".

Thank you

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
After one Result....Results Field does clear.. 
CoMAqORZyT

**Comment by jayaganeshkumar** [comment]
@avinashkranjan  I have done the required changes. Check it now!!

**Comment by jayaganeshkumar** [comment]
@avinashkranjan  In Python 3.8, it is working for me without any changes. Please check once again.

**Review by avinashkranjan — APPROVED** [review]
LGTM..🚀

**Comment by jayaganeshkumar** [comment]
@avinashkranjan  you approved changes or you merged the branch?

**Comment by avinashkranjan** [comment]
@all-contributors please add @jayaganeshkumar  for code and documentation

**Pull request merged**
