### PR TITLE
Bubble shooter game.

### LINKED ISSUE #806: Bubble shooter game using python
## Here is the screenshot 
bubbleshoot

I would like to work on this project .Please assign this issue to me @kaustubhgupta @antrikshmisri @santushtisharma10 @tamanna-verma

### PR DESCRIPTION
**Pull request by syamala27**
# Description
- The game is played using arrow keys.
- Bubbles pops if three or more match up using floodfill.

## Fixes #806

Replace `#806` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

# Screenshot
bubbleshoot

@antrikshmisri  @kaustubhgupta  @santushtisharma10 @tamanna-verma , please review the project and guide me if any changes are required.
Thank you :)

### CODE REVIEW

**Comment by santushtisharma10** [comment]
@syamala27 you copied from [here](https://github.com/justinmeister/bubbleshooter). All variable names, function name, everything is exactly same

**Comment by syamala27** [comment]
@santushtisharma10  I didn't know about plagiarism can I redo it.

**Comment by antrikshmisri** [comment]
@santushtisharma10 Yup, its exactly the same.

**Comment by syamala27** [comment]
> @santushtisharma10 @antrikshmisri I didn't know about plagiarism can I redo it. Sorry for the inconvenience, I will make some changes to the code and I will add new elements to the game.

**Comment by santushtisharma10** [comment]
@syamala27 instead of adding the new features to the exisiting code, if you can create this game on your own only then i can let you redo it.

**Comment by syamala27** [comment]
> @syamala27 instead of adding the new features to the exisiting code, if you can create this game on your own only then i can let you redo it.

I am glad to hear that mam ,definitely I will redo it .
Thankyou for giving me another chance.

**Comment by syamala27** [comment]
@santushtisharma10  @antrikshmisri  @kaustubhgupta, I updated the game please verify it.

## The changes which I have made:-
- Increased screen size
- Increased  number of balls 
- Added  more variety of colors 
- Added music
- Changed background-color
- Changed font (score)
-  Increased text size  
- Increased more rows 

##  Here I am sharing the screenshot 
bubbleshoot

**Review by kaustubhgupta — APPROVED** [review]

**Review by kaustubhgupta — COMMENTED** [review]
Add the readme file for this game

**Review by antrikshmisri — APPROVED** [review]

**Review by Kushal997-das — APPROVED** [review]
LGTM 💯

**Comment by santushtisharma10** [comment]
@syamala27 add the readme file

**Comment by syamala27** [comment]
@santushtisharma10 @kaustubhgupta  I have updated the readme file. 
please verify it .

**Review by santushtisharma10 — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
