### PR TITLE
PDF rotation API script

### LINKED ISSUE #1809: [GSSOC'23] PDF rotation Script
# Aim

- The script contains an API to rotate pdf's to the given angle

# Details

-Script contains an API implemented in Django aimed to rotate pdf at an angle given by the user.

### PR DESCRIPTION
**Pull request by alwenpy**
# Description

Added an API that developers can use to add the feature of pdf rotation

## Fixes #1809 

- #1809 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [x] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: \<PDF rotation API\>

Folder: \<pdf_rotation\>

Requirements: \<libraries like ninja API,PyPDF2\>

Script: \<api.py\>

Contributor: \<alwenpy\>

Description: \<rotates the pdf at the desired angle\>

### CODE REVIEW

**Comment by avinashkranjan** [comment]
Update the script not the `zip`

**Comment by alwenpy** [comment]
Deleted zip file since it is not needed.

**Comment by alwenpy** [comment]
I am adding a new feature so it is of level 2 or 3?

**Comment by avinashkranjan** [comment]
There's no script in this PR, Depending upon the type of Script it would either level2 or level3

**Comment by alwenpy** [comment]
Got it.Please merge this PR.

**Comment by alwenpy** [comment]
Added the scripts.

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Why is there a django project here, Just write a simple script.

**Comment by alwenpy** [comment]
django project replaced with the script and added a README.md

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
