### PR TITLE
added Morse Code Translator

### LINKED ISSUE #649: Morse Code Translator In Python
# Aim

- What is the objective of the Script
Create a Morse Code Translator In Python
# Details

- What features will your script have

Translate the given morse code to English

### PR DESCRIPTION
**Pull request by aishwaryachand**
# Description

added Morse Code Translator

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [X] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — COMMENTED** [review]
Upper case and lower case sensitivity is not handled. If I write lower case message, then the decrypted message needs to be in lower case only

**Comment by aishwaryachand** [comment]
> Upper case and lower case sensitivity is not handled. If I write lower case message, then the decrypted message needs to be in lower case only

I didn't get you . There are no distinctions between uppercase and lowercase letters used in Morse code.

**Comment by kaustubhgupta** [comment]
> > Upper case and lower case sensitivity is not handled. If I write lower case message, then the decrypted message needs to be in lower case only
> 
> I didn't get you . There are no distinctions between uppercase and lowercase letters used in Morse code.

If I encrypt the message " I am reviewing PRs", then get the morse code and then decrypt that code, the output would be "I AM REVIEWING PRS". It should be the same lower cases

**Comment by aishwaryachand** [comment]
capital letter and small letter have the same morse code .So when you write your message in small letter , the script converts it into capitals (as they have the same morse code) and gives an output.

**Comment by kaustubhgupta** [comment]
> capital letter and small letter have the same morse code .So when you write your message in small letter , the script converts it into capitals (as they have the same morse code) and gives an output.

oh, okay, I searched about it and you are right, I was not aware of this thing, apologies, you code works and therefore I have approved it

**Review by kaustubhgupta — APPROVED** [review]

**Review by santushtisharma10 — APPROVED** [review]
LGTM 💯

**Review by antrikshmisri — APPROVED** [review]

**Pull request merged**
