### PR TITLE
Create brick breaker game.py

### LINKED ISSUE #704: BRICK BREAKER GAME GUI
**Is your feature request related to a problem? Please describe.**
brick breaker game gui based

**Additional context**
I would like to do it as a gssoc particiapnt..

### PR DESCRIPTION
**Pull request by priyanka001tech**
# Description

BRICK BREAKER GUI GAME 

## Fixes #704 

Replace #704  with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by santushtisharma10 — CHANGES_REQUESTED** [review]
@priyanka001tech you have to make a folder of brick breaker game and add your python file in it. Also add a readme file

**Comment by priyanka001tech** [comment]
Okay @santushtisharma10 ..I'll do it.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@priyanka001tech I run your code in my local and i found there is an error . So the error is you didn't add the `bimg1.png` . That's the reason it give me error. It's better if you attach  the `bimg1.png` image along with your project . Moreover , You created only file instead folder and it is mandatory to create folder . 
And yeah add a little description about your project .

**Comment by kaustubhgupta** [comment]
@priyanka001tech @santushtisharma10 @Kushal997-das Look at this Repo code: https://github.com/Marishwaran99/BrickBreakerPy

That's why a lot of files were missing. A-Z code has been copied without even an inch modification. Highly discouraged proactise.

**Comment by Kushal997-das** [comment]
> @priyanka001tech @santushtisharma10 @Kushal997-das Look at this Repo code: https://github.com/Marishwaran99/BrickBreakerPy
> 
> That's why a lot of files were missing. A-Z code has been copied without even an inch modification. Highly discouraged practice.

I see @kaustubhgupta they are just try to spam GSSOC .

**Comment by priyanka001tech** [comment]
Ok,this time I'll try to code it as my own.

**Comment by priyanka001tech** [comment]
I have no such intensions to spam gssoc or anything else
this was my very first attempt so try to pardon my mistakes.
This time I'll try to do it correctly.

**Comment by kaustubhgupta** [comment]
> Ok,this time I'll try to code it as my own.

okay then,

**Pull request closed without merging**
