### PR TITLE
made GUI chat application

### LINKED ISSUE #686: GUI Chat application
# Aim

This is a simple GUI (Graphical User Interface) chat application where multiple users can connect with each other in a client-server architecture i.e the clients will interact with the help of the server.

# Details

The Python Chatbox uses the concept of Socket Programming & Multi-threading. There are two sections for the chatbot i.e server-side program called socketserver.py & client-side program namely chat.py. It allows a chat room or chat box to connect with multiple users at the same time.

### PR DESCRIPTION
**Pull request by subhangi2731**
# Description

This is a simple GUI (Graphical User Interface) chat application where multiple users can connect with each other in a client-server architecture i.e the clients will interact with the help of the server. This script file name is ‘client.py'(say) .
Since only the clients will interact the server script does not have a GUI.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have made the requirements.txt file and installed python packages

## Project Metadata

`` I have made the python chat box which is GUI Chat Application and made socketserver.py and chat.py and imported sockets imported socket library, Lists that will contains all the clients connected to the server and their names, Create a new socket for the server , bind the address of the server to the socket , function to start the connection, Listening to connection , accept connections and returns a new connection to the client and  the address bound to it.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [x] Others

Title: \<GUI chat application\>

Folder: \Chat-Application-GUI\>

Requirements: \<import socket and threading modules
from tkinter import *
from tkinter import font
from tkinter import ttk\>

Script: \<chat.py\>

Contributor: \<subhangi2731\>

Description: \<This is a simple GUI (Graphical User Interface) chat application where multiple users can connect with each other in a client-server architecture i.e the clients will interact with the help of the server.\>

### CODE REVIEW

**Comment by subhangi2731** [comment]
@avinashkranjan @kaustubhgupta please review and merge my pr

**Comment by subhangi2731** [comment]
@avinashkranjan please merge my pr

**Comment by kaustubhgupta** [comment]
> @avinashkranjan please merge my pr

Have some patience, it's not being reviewed yet :(

**Review by kaustubhgupta — COMMENTED** [review]
exactly the same code: https://www.youtube.com/watch?v=sopNW98CRag with only one change: in line 74, instead of `nick` it is `name`.

No readme file, wrongly updated PR template

**Comment by santushtisharma10** [comment]
Agreed @kaustubhgupta . the whole code is copied

**Comment by subhangi2731** [comment]
@kaustubhgupta @santushtisharma10 I had taken guide from resources as everyone does that as it was totally new to me but really sorry for inconvenience I will close this 2 prs

**Pull request closed without merging**
