### PR TITLE
Improved text-to-speech.py

### LINKED ISSUE #440: Text to Speech
**Describe the bug**
I can improve [this](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Text-To-Speech) directory of "Text to Speech" in a better way using tkinter. 

**Screenshots**
It will look like this:
tts

### PR DESCRIPTION
**Pull request by mehabhalodiya**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by mehabhalodiya** [comment]
I will create a README.md file for this script.

**Comment by kaustubhgupta** [comment]
@mehabhalodiya you are using Linux and I am running it on windows, maybe that's an issue but it will be resolved if you delete the file generated as soon as the user gets the output. I had this thing in mind from the beginning because user expects the audio output and no unnecessary files. 
 
Kindly delete the data.mp3 file uploaded in this PR, create the readme file for this script and implement file deletion mechanism in the script.

**Comment by kaustubhgupta** [comment]
@mehabhalodiya This script is not updated yet after so many commits

**Comment by mehabhalodiya** [comment]
Now what should I need to do?

**Comment by kaustubhgupta** [comment]
> Now what should I need to do?

https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/449#issuecomment-796411780

**Comment by mehabhalodiya** [comment]
Okay, I will do that by tomorrow.

**Comment by mehabhalodiya** [comment]
Can you help me with file deletion mechanism?
```
import os

path = "/home/oem/Amazing-Python-Scripts/Text/Text-To-Speech/Data.mp3"

os.remove(path)

print("Data.mp3 has been deleted.")
```

Should I have to write this piece of code?

**Comment by kaustubhgupta** [comment]
> Can you help me with file deletion mechanism?
> 
> ```
> import os
> 
> path = "/home/oem/Amazing-Python-Scripts/Text/Text-To-Speech/Data.mp3"
> 
> os.remove(path)
> 
> print("Data.mp3 has been deleted.")
> ```
> 
> Should I have to write this piece of code?

Try this:
```python
def Text_to_speech():
    Message = entry_field.get()
    speech = gTTS(text = Message)
    speech.save('Data.mp3')
    playsound('Data.mp3')
    os.remove('Data.mp3')
```

**Review by kaustubhgupta — APPROVED** [review]
💯

**Comment by kaustubhgupta** [comment]
@santushtisharma10 @antrikshmisri

**Comment by kaustubhgupta** [comment]
@santushtisharma10 @antrikshmisri

**Review by antrikshmisri — APPROVED** [review]
LGTM 🚀

**Review by avinashkranjan — APPROVED** [review]
LGTM..Great Work @mehabhalodiya

**Comment by avinashkranjan** [comment]
@all-contributors please add @mehabhalodiya for code and documentation

**Pull request merged**
