### PR TITLE
Adding Random Quotes Generator Script

### PR DESCRIPTION
**Pull request by pavansai5448**
# Description
This pull request aims to add the new Python script "Random Quotes Generator", Which generates the random quotes based on the given category.

## Screenshot
image

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: \<write script title here\>

Folder: \<type the folder name that contains your script\>

Requirements: \<type the name of text file containing the required to install python packages, type None if no file required\>

Script: \<Enter the name of the ``.py`` file (The main entry point of the program)\>

Arguments: \<enter any arguments that the script needs but `-` separeted like: h-c-m\>

Contributor: \<Enter your Github handle/username without url\>

Description: \<Enter a one line description that describes your script. Also, explain the arguments usage here\>

### CODE REVIEW

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Add a `README` file

**Comment by 1e9abhi1e10** [comment]
@pavansai5448 change the title of the PR to something like `Adding Random Quotes Generator Script`

**Comment by 1e9abhi1e10** [comment]
@pavansai5448 Please open an issue if it already exists then reference it here

**Comment by avinashkranjan** [comment]
Mention the Issue number, If issue not created, Create an Issue.

**Pull request closed without merging**
