### PR TITLE
Titanic Survival Prediction Model

### PR DESCRIPTION
**Pull request by Dhanush2612**
ML model to predict Titanic Survival.
Readme file and sample output image has been included.

Fixes: #509

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
This is the wrong way of implementing this. Please refer to the idea given in one of the issues to you

**Comment by Dhanush2612** [comment]
May I please know the changes that you require?

**Comment by kaustubhgupta** [comment]
> May I please know the changes that you require?

please read this issue discussions for knowing what I am referring here

**Comment by kaustubhgupta** [comment]
@Dhanush2612 updates?

**Comment by Dhanush2612** [comment]
Do you want me to make this change?

open​(​'./Salary Predictor/models/random_forest2_model.sav'​, ​'rb'​) ​as​ ​f​:
   ​random_forest_model​ ​=​ ​pickle​.​load​(​f​)

**Comment by kaustubhgupta** [comment]
> Do you want me to make this change?
> 
> open​(​'./Salary Predictor/models/random_forest2_model.sav'​, ​'rb'​) ​as​ ​f​:
>    ​random_forest_model​ ​=​ ​pickle​.​load​(​f​)

No, no! Look at how he implemented it. One .py file for training, one file for running the saved model by taking inputs from the user from the terminal.

**Comment by Dhanush2612** [comment]
Ok

**Comment by kaustubhgupta** [comment]
@Dhanush2612 Updates on this?

**Comment by Dhanush2612** [comment]
@kaustubhgupta 
I have semester exams going on, so I working on it when ever I am free.

**Comment by kaustubhgupta** [comment]
@Dhanush2612 you can take a max of 2 more days to complete it.

**Comment by kaustubhgupta** [comment]
@Dhanush2612 have you started working on this?

**Comment by Dhanush2612** [comment]
Can one more participant take part in this issue? So that he/she can continue where I left off or fix the bug?

**Comment by kaustubhgupta** [comment]
@Dhanush2612 nope, either this issue will be closed or assigned to someone else.

**Comment by Dhanush2612** [comment]
@kaustubhgupta 
You want me to create .py files for train and test datasets and read them in model as .py files?

**Comment by Dhanush2612** [comment]
@kaustubhgupta 
You don't want this kind of code for reading dataset into a python model?
df = pd.read_csv('train.csv')

**Comment by kaustubhgupta** [comment]
@Dhanush2612 look at these PRs for reference: #556, #638

**Comment by Dhanush2612** [comment]
@kaustubhgupta So you want the code to be like this
df = pd.read_csv('./Titanic Survival Prediction/dataset/test.csv')
instead of
df = pd.read_csv('train.csv')

**Comment by Dhanush2612** [comment]
@kaustubhgupta 
What else?

**Comment by Dhanush2612** [comment]
Next do you want me to add a stream bit file for model like this?

from sklearn.linear_model import LogisticRegression
import pickle
model = LogisticRegression()
model.fit(xtrain, ytrain)
# save the model to disk
pickle.dump(model, open(model_file_path, 'wb'))
model = pickle.load(open(model_file_path, 'rb'))
result_val = model.score(xval, yval)
result_test = model.score(xtest, ytest)

**Comment by Dhanush2612** [comment]
Or this?
with open('././Titanic Survival Prediction/dataset/titanic_pred.csv, 'rb') as f:
   random_forest_model = pickle.load(f)

**Comment by kaustubhgupta** [comment]
@Dhanush2612  What we require is that:
- One file where you train the model and save the best model as .sav
- Another file where you load the model and allow users to give inputs for the various parameters of the model to give the result.
- The CSV dataset file.
- The training model file and prediction file needs to be .py and not notebooks.
- Make sure to configure all the paths (./Titanic Survival Prediction/) correctly and run the script locally too before pushing the changes.

You need to do this today only.

**Comment by Dhanush2612** [comment]
How do I do this?
Another file where you load the model and allow users to give inputs for the various parameters of the model to give the result.

**Comment by kaustubhgupta** [comment]
> How do I do this?
> Another file where you load the model and allow users to give inputs for the various parameters of the model to give the result.

For the last time, I am requesting you to have a look at these PRs:  #556, #638

**Comment by Dhanush2612** [comment]
Are you referring to pickled model? 
Another file where you load the model and allow users to give inputs for the various parameters of the model to give the result

**Comment by Dhanush2612** [comment]
@kaustubhgupta I have added files as per your request and script file, prediction file in .sav format is also included.

**Comment by Dhanush2612** [comment]
@kaustubhgupta Please refer to the files in the latest PR with changes above 
cf2d85f

**Comment by Dhanush2612** [comment]
@kaustubhgupta The tests for PR are failing, shall I create new PR regarding this?

**Comment by kaustubhgupta** [comment]
These are the errors returned by the test:

**Comment by kaustubhgupta** [comment]
@Dhanush2612 Leave this issue, you don't know what you are submitting, even after several reminders about what to submit, you didn't get the point.

**Pull request closed without merging**
