### PR TITLE
Added weight converter

### LINKED ISSUE #740: Weight Converter GUI
# Aim

- Program to design a GUI based application using tkinter, to convert weights in kg to other units.

# Details

- I will create a GUI based weight converter that accepts a kilogram input value and converts that value to Carat, Gram, Ounce, Pound, Quintal and Tonne (in decreasing order) when the user clicks the Convert button.

### PR DESCRIPTION
**Pull request by mehabhalodiya**
# Description
I have created a GUI based weight converter that accepts a kilogram input value and converts that value to Carat, Gram, Ounce, Pound, Quintal and Tonne when the user clicks the Convert button.

I have arranged weight conversions in decreasing order like starting from Carat to Tonne(mentioned above).

Output of the code:

wc

One more feature: It is editable :)

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(above in description) that prove my feature is effective or that my feature works.

### CODE REVIEW

**Comment by mehabhalodiya** [comment]
Let me know if it works well so that I can create a README.md file for this.

**Review by santushtisharma10 — CHANGES_REQUESTED** [review]
@mehabhalodiya the code is working fine, add the readme file

**Comment by mehabhalodiya** [comment]
@santushtisharma10 Kindly review this.

**Review by santushtisharma10 — APPROVED** [review]
@mehabhalodiya 💯

**Comment by santushtisharma10** [comment]
@Kushal997-das

**Comment by mehabhalodiya** [comment]
@kaustubhgupta @antrikshmisri @Kushal997-das Kindly review this.

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
Shift these labels (Carat, Gram) to right side like the ones written on the left (kg to ct)

image

**Comment by mehabhalodiya** [comment]
Like this? Should I modify code according to below one?

weightconv

**Comment by kaustubhgupta** [comment]
> Like this? Should I modify code according to below one?
> 
> weightconv

correct

**Comment by mehabhalodiya** [comment]
@kaustubhgupta I have made suggested changes. Kindly review it.

**Review by kaustubhgupta — APPROVED** [review]

**Review by antrikshmisri — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]
LGTM

**Pull request merged**
