### PR TITLE
GitHub user scraper

### LINKED ISSUE #947: Trending GitHub Users Fetcher (GUI)
# Aim

To scrap details of users who are trending.

# Details

Scrapping can be done using any library of your choice. Various filters you need to provide:
- Based on location (India, Egypt...)
- Based on language (Python, Java...)
- Based on the date (Today, Week, or Month)

The data needs to be stored as an SQLite database and then displayed in the GUI application. You can opt for any GUI library: Kivy, Tkinter, Pygame, or Dear GUI.

### PR DESCRIPTION
**Pull request by Ayushjain2205**
# Description

Python script to fetch trending users from github

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [x] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: Github User Scraper

Folder: Github-User-Scraper

Requirements: requirements.txt

Script: scraper.py

Arguments: none

Contributor: Ayushjain2205

Description: Scraper trending GitHub users based on language and time frame picked by the user

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
- Add a progress bar to show the user that the scrapping progress has started and ended.
- After scrapping one time, if I click again on scrap users, the application throws the error:
image

You can handle it by prompting that this combination already scrapped or whatever you wish.

- After scrapping one category (Python for instance), If I scrap another language, the results are displayed below the previous one. You should only display that particular language repos. You can fix this by creating different tables for each language.

**Comment by Ayushjain2205** [comment]
@kaustubhgupta Do I need to make tables for all possible unique combinations?

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 no, just make tables for different languages. The weekly and monthly data can be stored in that specific language table.

**Comment by Ayushjain2205** [comment]
OK got it...working on the changes will be done by tomorrow

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  I have solved the Bug without adding tables for individual languages, because adding variable table name was giving me some issues.
I have made the unique field non unique and while fetching I am only fetching distinct fields.
I have made the Date range and language as a table column and it gets printed with the records in the UI so the user can easily see what they scraped.

**Review by kaustubhgupta — APPROVED** [review]

**Review by santushtisharma10 — APPROVED** [review]

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  Changes made to PR template

**Review by antrikshmisri — APPROVED** [review]

**Pull request merged**
