### PR TITLE
Email Scheduler

### LINKED ISSUE #2196: [Script]: Email Scheduler
### Aim

Scheduling email to a particular time

### Details

Will be using SMTP library to send email

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Juhibhojani**
# Description

Added a file that schedules email and send them via SMTP

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project metadata in the PR template.
- [ ] I have created the ``requirements.txt`` file if needed. 

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt is needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [x] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: Email_scheduler.py

Folder: Email-Sender

Requirements: None

Script: Email_scheduler.py

Contributor: Juhibhojani

Description: Scheduling Email

### CODE REVIEW

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Add a `README.md` file

**Comment by Juhibhojani** [comment]
I have made the necessary changes, please review it now. @avinashkranjan

**Comment by avinashkranjan** [comment]
Conflicts are still there.

**Comment by Juhibhojani** [comment]
image

I can't resolve these conflicts

**Comment by Juhibhojani** [comment]
Okay

**Pull request closed without merging**
