### PR TITLE
Counting number of fingers using open cv

### LINKED ISSUE #550: Counting Number of fingers using OpenCV
# Aim

- This project will help us to count the number of fingers in a given image using OpenCV based on Convex Hull Method.

### PR DESCRIPTION
**Pull request by undetectablevirus**
# Description
Added Code for the issue: Counting the number of fingers in a given image using OpenCV based on Convex Hull Method.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by undetectablevirus** [comment]
@kaustubhgupta Please review this.

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
Is this some bug?
image

**Comment by undetectablevirus** [comment]
I will look into it and correct it as soon as possible. Thanks for the cooperation

**Comment by kaustubhgupta** [comment]
@undetectablevirus updates on this?

**Comment by kaustubhgupta** [comment]
@undetectablevirus are you working on this?

**Comment by kaustubhgupta** [comment]
@undetectablevirus as you haven't responded after multiple reminders, this PR and associated issue will be closed.

**Pull request closed without merging**
