### PR TITLE
Script added for show List files in a directory

### LINKED ISSUE #1527: [gssoc'23] show List files in a directory
Hi @avinashkranjan 
# Aim

- What is the objective of the Script
- to display list of file content available in current directory

# Details

- What the features will your script have
script shows how to get the list of a specific directory in python using the os module.

Please assign it under gssoc'23 label
Thank you

### PR DESCRIPTION
**Pull request by gulshanjakhon**
# Description
Python Script added for 
Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #1527 

#1527 
## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [none  ] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [x] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: show List files and folders available in a directory

Folder: List_Files_and_Folder_in_a_directory

Requirements: Readme.md

Script: List_Files_and_Folder_in_a_directory.py

Arguments: \<enter any arguments that the script needs but `-` separeted like: h-c-m\>

Contributor: [Gulshan Kumar Jakhon](https://github.com/gulshanjakhon)

Description: These scripts allow you to display all the files and folder available in the directory

### CODE REVIEW

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Add `README` file

**Comment by gulshanjakhon** [comment]
Hi @avinashkranjan 
in this request, I have solved the issue of no Python Script to fetch all links from the webpage [gssoc23] #1673 
Please review it

**Comment by gulshanjakhon** [comment]
Hi @avinashkranjan please review again, and let me know it there is some error.

Thank You
Gssoc23 Contributor

**Comment by gulshanjakhon** [comment]
hi @avinashkranjan please review this PR

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
