### PR TITLE
Added Reddit-scraping-and-flair-detection folder

### LINKED ISSUE #161: Scraping and flare detection
# Aim

- Scraping r/india website for collecting data
- Using ml for flare detection

### PR DESCRIPTION
**Pull request by shubhigupta991**
# Description

Added Reddit-scraping-and-flair-detection folder

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by avinashkranjan** [comment]
@shubhigupta991 How does this solve #56 Issue?

**Comment by shubhigupta991** [comment]
> @shubhigupta991 How does this solve #56 Issue?

really sorry i linked the wrong issue. I have corrected my mistake its issue #161

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
.

**Review by avinashkranjan — APPROVED** [review]
LGTM 💯 Great Job

**Comment by avinashkranjan** [comment]
@all-contributors please add @shubhigupta991  for code and documentation

**Pull request merged**
