### PR TITLE
added songs of artist

### PR DESCRIPTION
**Pull request by gargnityansh**
# Description
Please enter spotify api details in the config for the working of songs_of_artist file.
Created 2 files:- songs_of_artist.py which finds the songs of an artist whose name is being provided using spotify api. And the other one is config.py in which you have to pass your spotify api details inorder to configure spotify authentication.

## Fixes  #(153)
arijit

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Kindly add a Readme file...Rest LGTM

**Comment by gargnityansh** [comment]
> Kindly add a Readme file...Rest LGTM

Created

**Comment by gargnityansh** [comment]
@avinashkranjan please have a review.

**Review by avinashkranjan — APPROVED** [review]
LGTM..🚀

**Comment by avinashkranjan** [comment]
@all-contributors please add @gargnityansh for code and documentation

**Pull request merged**
