### PR TITLE
🚀Added Pygames 

### PR DESCRIPTION
**Pull request by Lakhankumawat**
# Description

Fixes: #583 

<h2> I have added two pygames . </h2>
1. Rock Paper Scissor<br>
2. Tic Tac Toe <br>

<br> <b>Rock Paper Scissor </b> For this i have made a folder named Rock Paper Scissor and in it i have my _RockPaperScissor.ipynb_ file alongwith _README file_ . The _code runs totally fine_ and shows the expected outputs.I have implemented it using _Tkinter_ library . For more check out _README.md 2nd_ given below in documentation .

<br> <b>TicTacToe </b> For this i have made some changes in [`Tictactoe-Using-Minmax`](https://github.com/Lakhankumawat/Amazing-Python-Scripts/tree/master/Tictactoe-Using-Minmax)
Added _README_ file alongwith _TicTacToe.ipynb_ for more please check out _README.md 1st_ given below in documentation .

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [X] Yes
- [ ] No

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md 1st `](https://github.com/Lakhankumawat/Amazing-Python-Scripts/blob/master/Tictactoe-Using-Minmax/README.md) [`Template for README.md 2nd `](https://github.com/Lakhankumawat/Amazing-Python-Scripts/blob/master/RockPaperScissor/README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
**Kindly Merge This With Label Gssoc'21**

**Comment by kaustubhgupta** [comment]
Where is the issue for this PR?

**Comment by Lakhankumawat** [comment]
This PR doesn't belong to any issues mentioned in issues section . It is basically adding additional files /contents to repo which was not there earlier . As i have mentioned above  kindly  see 👀 there .

**Comment by kaustubhgupta** [comment]
> This PR doesn't belong to any issues mentioned in issues section . It is basically adding additional files /contents to repo which was not there earlier . As i have mentioned above kindly see 👀 there .

All the PRs in this repo are linked to an issue. Create a new issue for this

**Comment by Lakhankumawat** [comment]
Ok i will create such issue and mention it here in this PR itself after that i think it will be okay to merge 🙂

**Review by kaustubhgupta — COMMENTED** [review]
There are many issues here:
- Firstly, this is not your code. In the notebook file (which was not supposed to be added), there is a link to this youtube video https://www.youtube.com/watch?v=qikY7HetH14 and the source code is available at https://www.dropbox.com/s/8t8k08yx5gvq1w6/rpsGUI.py?dl=0

- Tic-tac-toe game was made in this tutorial https://www.youtube.com/watch?v=pc7XhHxSgrM&t=1s and source code is available at https://github.com/AlejoG10/python-tictactoe-yt

This is not acceptable at all and therefore we cannot proceed with this

**Comment by Lakhankumawat** [comment]
Great , But i didn't copied from anywhere i did it on my own 🙂 your wish .

**Comment by kaustubhgupta** [comment]
The confusion was cleared

**Pull request closed without merging**
