### PR TITLE
Adding the Football Player Club Info

### PR DESCRIPTION
**Pull request by shahidshakil**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by shahidshakil** [comment]
First iteration of the feature. I am working on making the code more object-oriented and readable. The Documentation would follow in the following pull requests.

**Review by avinashkranjan — APPROVED** [review]
LGTM..You can go ahead create a ReadMe and make changes you want as well

**Comment by shahidshakil** [comment]
Refactored the code to make it more modular.

**Comment by shahidshakil** [comment]
Refactored the code to make it more modular.

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
LGTM....
Just Remove the Empty lines..and add some comments.

**Comment by avinashkranjan** [comment]
@shahidshakil Are you going to add any more features?? or the ReadMe??

**Comment by shahidshakil** [comment]
> @shahidshakil Are you going to add any more features?? or the ReadMe??

I will perform the requested changes and add a readme file.

**Comment by avinashkranjan** [comment]
@shahidshakil Any Updates?

**Review by avinashkranjan — APPROVED** [review]
Since You're not making any more amendments.. I'm Merging it here

**Comment by avinashkranjan** [comment]
@all-contributors please add @shahidshakil  for code

**Pull request merged**
