### PR TITLE
Mini Google Assistant 

### LINKED ISSUE #726: Mini Google Assistant
# Aim

- To build a mini google assistant.

# Details

- A mini google assistant using some python libraries. Kindly assign me this issue, @avinashkranjan Sir.

### PR DESCRIPTION
**Pull request by A-kriti**
# Description

Added a new folder "Mini Google Assistant" containing python and a readme file which finally fixes issue no. 726.

## Fixes #726

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [✓] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [✓] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [✓] My code follows the style guidelines(Clean Code) of this project
- [✓] I have performed a self-review of my own code
- [✓] I have commented my code, particularly in hard-to-understand areas
- [✓] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [✓] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
@A-kriti Why there are Ghost filter files in this PR?

**Comment by A-kriti** [comment]
@kaustubhgupta I am trying to fix those.

**Comment by kaustubhgupta** [comment]
@A-kriti Create a new PR with a new branch for this issue. I am closing this one as it is cluttered.

**Comment by kaustubhgupta** [comment]
@A-kriti Wil you make new PR or shall I assign this issue to someone else?

**Comment by A-kriti** [comment]
@kaustubhgupta I'll make a pr!

**Comment by kaustubhgupta** [comment]
@A-kriti?

**Comment by A-kriti** [comment]
@kaustubhgupta Sir, I'll do it by tomorrow! sorry for the delay

**Pull request closed without merging**
