### PR TITLE
Created bmi calculator gui for issue #1949

### LINKED ISSUE #1949: [Script]: BMI calculator gui
### Aim

This is a simple BMI (Body Mass Index) calculator implemented in Python using a Graphical User Interface (GUI) with Tkinter.

### Details

Tkinter: This is the standard Python GUI library used to create the graphical interface for the BMI calculator.

It will calculate bmi of person.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by bhavya1857**
# Description

Just created the calculator gui bmi.

## Type of change

_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] I have added the project meta data in the PR template.
- [ ] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators

Title: bmi calculator gui 

Folder: \<type the folder name that contains your script\>

Requirements: tkinter

Script: \<Enter the name of the ``.py`` file (The main entry point of the program)\>

Arguments: \<enter any arguments that the script needs but `-` separeted like: h-c-m\>

Contributor: @bhavya1857

Description: \<Enter a one line description that describes your script. Also, explain the arguments usage here\>

### CODE REVIEW

**Review by avinashkranjan — APPROVED** [review]

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Make this is a .py file and add a README file as well

**Comment by bhavya1857** [comment]
@avinashkranjan why do i have to make the readme file? It already there.

**Comment by avinashkranjan** [comment]
Don't make two PRs, Create a Single PR by closing both active PRs

**Comment by bhavya1857** [comment]
@avinashkranjan hi, i just wanted to know that why have you opened this PR again?

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Make this .py file and add a `README.md` file

**Pull request closed without merging**
