### PR TITLE
Added Body Detection

### LINKED ISSUE #533: Body Detection
I want to work on this project named Body Detection.
@avinashkranjan  please assign me for this project.
I am a participant of GSSOC'21 and want to contribute on this project

### PR DESCRIPTION
**Pull request by Avishake007**
# Description
Here I have added added Body Detection feature which detect your body using full-body cascade xml file.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)
## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.
BodyDetection

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
Is this bug from my side or something else?
image

**Comment by Avishake007** [comment]
@kaustubhgupta  its working when I am running like this
BodyDetection(2)
 This is the structure
BodyDetection(3)

**Comment by kaustubhgupta** [comment]
@Avishake007 I still not able to run your script. Can you add a GIF to your README showing the demo of your script?

**Comment by kaustubhgupta** [comment]
@antrikshmisri @santushtisharma10 Can you confirm this script working?

**Comment by antrikshmisri** [comment]
> @antrikshmisri @santushtisharma10 Can you confirm this script working?

Sure , will get back to you in a min.

**Review by antrikshmisri — APPROVED** [review]
@kaustubhgupta The script is working fine.

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta The script is working fine.

Okay then👍💯

**Review by kaustubhgupta — APPROVED** [review]

**Review by santushtisharma10 — APPROVED** [review]

**Pull request merged**
