### PR TITLE
added disk space analyzer script

### LINKED ISSUE #1739: Disk Space Analyzer [GSSoC'23]
# Aim

The aim of the script is to analyze disk space usage in a specified directory and provide a summary of the sizes of files and folders within that directory. The script will help users gain insights into the distribution of disk space and identify the largest files and folders.

# Details

The script will have the following features:

1. Directory Selection: The script will prompt the user to specify the directory path they want to analyze or accept it as a command-line argument.

2. File and Folder Analysis: The script will recursively scan the specified directory and calculate the size of each file and folder within it.

3. Sorting by Size: The script will sort the files and folders based on their sizes in descending order, with the largest ones displayed first.

4. Display: The script will output the names and sizes of the files and folders in a readable format.

5. Error Handling: The script will handle cases where the specified directory does not exist or is not accessible. It will provide appropriate error messages to the user.

With these features, the script will enable users to efficiently analyze disk space usage and identify space-consuming files and folders within a directory.

Request @avinashkranjan @Yashbhadiyadra , to kindly assign this task to me, to contribute under GSSoC'23. Thanks!

### PR DESCRIPTION
**Pull request by prernamittal**
# Description

Script analyzes disk space usage in a specified directory and provides a summary of the sizes of files and folders within that directory. This PR resolves issue #1739

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:

- [x] Automation

Title: Disk Space Analyzer

Folder:  Disk Space Analyzer

Requirements: none

Script: DiskSpaceAnalyzer.py

Arguments: none

Contributor: @prernamittal 

Description: The aim of the script is to analyze disk space usage in a specified directory and provide a summary of the sizes of files and folders within that directory. The script will help users gain insights into the distribution of disk space and identify the largest files and folders.

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
please check this PR @avinashkranjan @1e9abhi1e10

**Comment by Abhinavcode13** [comment]
@1e9abhi1e10 please merge this PR bro , thanks

**Comment by prernamittal** [comment]
Hello @1e9abhi1e10 @Abhinavcode13 @avinashkranjan kindly look into this PR!

**Comment by avinashkranjan** [comment]
Resolve the Conflicts

**Pull request merged**
