### PR TITLE
Tic-Tac-Toe

### PR DESCRIPTION
**Pull request by nitya123-github**
created a simple Tic-Tac-Toe game using random number

### CODE REVIEW

**Comment by avinashkranjan** [comment]
Hey @nitya123-github, please create an Issue for the Same, and is this for SWoC. If yes, then it would only be counted after 4th Jan, So should I wait till then for merging?

**Comment by nitya123-github** [comment]
yes its for swoc!  no problem merge it after jan4

**Comment by avinashkranjan** [comment]
Sure @nitya123-github, till then Kindly create an issue for the same

**Comment by nitya123-github** [comment]
created a todo app with user interface

**Comment by nitya123-github** [comment]
is my pull requested counted for swoc?

**Comment by avinashkranjan** [comment]
@nitya123-github Kindly Remove Todo Script from the PR..

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
@nitya123-github Kindly Remove Todo Script from the PR..

**Comment by avinashkranjan** [comment]
Since there are no more further updates I'm closing the Issue and PR as Invalid..

**Pull request closed without merging**
