### PR TITLE
Added Base-N-Calc Files

### LINKED ISSUE #957: Base-N Calculator
# Aim

- A Python calculator that can convert numbers from base-X to base-Y. Example: `` Decimal to Binary ``, `` Binary to Octal ``, `` Base 3 to Base 6 ``, ..etc.

# Details

- The script will not be limited to the known bases of Binary, Octal, Decimal, and Hexadecimal. The user will be able to enter/ convert-to the desired base number.
- The Script will be able to also deal with decimal numbers.
- Imparative approach will be used. (No external libraries to do the conversion job)

# Contribution Event

- GSSOC

### PR DESCRIPTION
**Pull request by XZANATOL**
# Description

Added Base-N calculator.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present then type in ``Requirments`` none => ``Requirments: none``

Category:
- [x] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: Base_N Calculator

Folder: Base-N_Calc

Requirments: none

Script: script.py

Arguments: none

Contributor: XZANATOL

Description: A GUI that will allow you to convert a number of base-X to base-Y as long as X&Y > 1.

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
Just a minor change:

**Comment by XZANATOL** [comment]
Done

**Review by kaustubhgupta — APPROVED** [review]

**Review by antrikshmisri — APPROVED** [review]

**Review by Kushal997-das — APPROVED** [review]
LGTM 💯

**Review by santushtisharma10 — APPROVED** [review]
LGTM

**Pull request merged**
