### PR TITLE
Making the entire repository menu driven

### LINKED ISSUE #831: Making the Whole Project/Repo Menu-Driven
**Is your feature request related to a problem? Please describe.**
Changing directories looking for scripts  to use one by one will be quite a headache.

**Describe the solution you'd like**
Making it a menu-driven script, where a user can select the option and the specific script will run (can take arguments too if needed at runtime) in sort like `Lazy Script` if you are aware of.

## Let me brief you about what you have to do on that issue:

1.  Make a menu-driven script which will perform the task as per selected option.
2. There are 100+ scripts currently so we need to provide all in the menu. 
**_Which can be done in the following ways_**  
   -  Scripts can be further categorized into sub categories 
       - Automation 
       - AI/ML
       - Calculators
       - Games
       - Fun
       - Scrappers
       - Bots 
      **_and More_** 
    - It'll help in searching through the numerous script easy
3. Give all the folder 777 permission for the execution of python files
4. Do provide comments while doing scripting
5. Be aware of file path as per linux system `ie. /root/your_filename` while working on github 
6. **Follow all the guidelines provided**

### Marking Guidelines

- Since This is a big Issues, Multiple contributors are welcome to contribute to the script, Depending on the Contribution PR level would be marked..the Issue would be a `Level3`, Each Linked PR would be of Minimum `Level2`.

@kaustubhgupta @antrikshmisri @santushtisharma10 Kindly Helpout the Contributors working on this particular Issue..As this one is a complex issue..If Any Issues, DM me on Discord..

Happy Coding..👨🏻‍💻

### PR DESCRIPTION
**Pull request by devRawnie**
# Description

Started the code for making the entire repository menu driven

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
@devRawnie I will review your PR after the database updation script works fine. Also, I am seeing a lot of issues will be incoming in this demo script. The requirements are the major issue plus the arguments. We will figure out all the issues

**Comment by devRawnie** [comment]
> @devRawnie I will review your PR after the database updation script works fine. Also, I am seeing a lot of issues will be incoming in this demo script. The requirements are the major issue plus the arguments. We will figure out all the issues

Sure

**Comment by kaustubhgupta** [comment]
@devRawnie Now the action is working properly and we can work on your issue. I would like you to pull the latest changes in your local system and then report what challenges you are facing. If you want, you can create separate issue other than the master issue (#831) for better clarity

**Comment by devRawnie** [comment]
Ok I am on it. Will revert back shortly

**Comment by devRawnie** [comment]
Kindly refer to #1071 issue for problems related to the menu driven script.

**Pull request closed without merging**
