### PR TITLE
The maximize button was not working

### PR DESCRIPTION
**Pull request by mahi0601**
#175 
I have changed the color and geometry . Now it can be  maximized. I have adjust the sizes of the buttons and color of the text in the button. Now you can increase the size or et a better view with maximizing the screen.

# Description

I have fixed the maximizing issue of the screen 

## Fixes #(175)

Replace `175` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [X ] Yes

## Type of change

_Please delete options that are not relevant._

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by mahi0601** [comment]
It's been two days but the checking hasn't passed yet

**Comment by avinashkranjan** [comment]
Resolve the Conflicts and What Difference does that maximize button make.. It was disabled cause it didn't have any purpose.. If you are working on that issue the maximize button to maximize the calculator along with the buttons.

**Comment by mahi0601** [comment]
No I was trying to just enable the maximizing button

**Comment by avinashkranjan** [comment]
> No I was trying to just enable the maximizing button

It didn't have any purpose so it was disabled..Would you work on maximizing function or should I close this and you can work on some other issue

**Comment by mahi0601** [comment]
No close this issue I will work on others

**Pull request closed without merging**
