### PR TITLE
Quiz Application - GUI

### LINKED ISSUE #460: Quiz Application GUI
Hello, I am a GSSoC '21 participant, I would like to contribute to this repository.

## Aim ##
Quiz Application GUI with Tkinter

## Description ##
The user will be allowed to choose between multiple categories, as well as difficulty levels. The score is calculated and displayed at the end.

### PR DESCRIPTION
**Pull request by soumyavemuri**
# Description

A Quiz application made with Python's Tkinter GUI toolkit. The quiz consists of 10 questions in total and the user can attempt a quiz on a category of their preference.

The application allows the user can choose from a range of categories; Movies, Television, Science and Nature, Anime and Manga, Mathematics, General Knowledge, Computers, Cartoons and many more. The user is also allowed to choose the difficulty level they'd like to attempt (Hard, Medium, Easy).

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — APPROVED** [review]
Pretty clean implementation, works perfectly! Good Job @soumyavemuri 💯

**Comment by kaustubhgupta** [comment]
@santushtisharma10 @tamanna-verma @antrikshmisri

**Review by sadiqabubakar526 — APPROVED** [review]

**Review by antrikshmisri — APPROVED** [review]
@soumyavemuri @kaustubhgupta  LGTM 💯

**Review by avinashkranjan — APPROVED** [review]
LGTM..🚩

**Comment by avinashkranjan** [comment]
@all-contributors please add @soumyavemuri  for code and documentation

**Pull request merged**
