### PR TITLE
I have created a Stone Paper Scissors Game using Python

### PR DESCRIPTION
**Pull request by Tanujcbe**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Tanujcbe** [comment]
I did this project for Hacktoberfest

**Comment by avinashkranjan** [comment]
@Tanujcbe Kindly Create a Issue for the Same..

**Comment by avinashkranjan** [comment]
@Tanujcbe Kindly create a Readme and add few SS..

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Add comments to the code where required..

**Review by avinashkranjan — APPROVED** [review]
LGTM.. 💯

**Comment by avinashkranjan** [comment]
@all-contributors please add @Tanujcbe for code

**Pull request merged**
