### PR TITLE
AI-Integrated-Ludo-Game Added

### LINKED ISSUE #604: AI Integrated Ludo Game Made In Python Tkinter
# Aim

Play Game With Artifical Intelligence at the time of loniliness

# Details

I make AI-Integrated Ludo Game in Python Tkinter...... In this, You can play with computer as well as your friends

I am also a gssoc'21 participant....please assign me to here @avinashkranjan

### PR DESCRIPTION
**Pull request by SamarpanCoder2002**
A Python Tkinter Game, Where you can play with computer as well as your friends

# Description

AI-Integrated-Ludo-Game Added.... Pillow module have to download manually by opening terminal as: `pip install pillow`

## Fixes #604

Replace `#604` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

Sample GIF

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
@avinashkranjan I don't know if this should be included or not because the codebase is huge

**Comment by SamarpanCoder2002** [comment]
> @avinashkranjan I don't know if this should be included or not because the codebase is huge and It will take a long long time to review which is out of scope. It's a standalone project!

So, what I can do.... ??? Can I close this pull request or do any modifications?

**Comment by kaustubhgupta** [comment]
> > @avinashkranjan I don't know if this should be included or not because the codebase is huge and It will take a long long time to review which is out of scope. It's a standalone project!
> 
> So, what I can do.... ??? Can I close this pull request or do any modifications?

Nope, wait for his response

**Comment by SamarpanCoder2002** [comment]
> > > @avinashkranjan I don't know if this should be included or not because the codebase is huge and It will take a long long time to review which is out of scope. It's a standalone project!
> > 
> > 
> > So, what I can do.... ??? Can I close this pull request or do any modifications?
> 
> Nope, wait for his response

Ok...waiting

**Comment by SamarpanCoder2002** [comment]
Any response from @avinashkranjan @kaustubhgupta ??

**Comment by kaustubhgupta** [comment]
> Any response from @avinashkranjan @kaustubhgupta ??

nope,

**Comment by kaustubhgupta** [comment]
> @avinashkranjan I don't know if this should be included or not because the codebase is huge and It will take a long long time to review which is out of scope. It's a standalone project!

@antrikshmisri @santushtisharma10 what are your thoughts on this?

**Comment by antrikshmisri** [comment]
@SamarpanCoder2002 This is a full fledged project and to review this will take a really long time. I would suggest you to decrease the scope of this project to make it fit for this codebase

**Comment by kaustubhgupta** [comment]
Updates: Conveyed the message to PA, he will respond soon

**Comment by avinashkranjan** [comment]
Hey @SamarpanCoder2002 As the Mentor Suggested, your Script is a project in itself, We are looking for compact script to 
to automate manual tasks..So, Closing it for now..

**Comment by SamarpanCoder2002** [comment]
> Hey @SamarpanCoder2002 As the Mentor Suggested, your Script is a project in itself, We are looking for compact script to
> to automate manual tasks..So, Closing it for now..

Ok no problem

**Pull request closed without merging**
