### PR TITLE
Added (DownTube) Youtube Video/Playlist Downloader

### LINKED ISSUE #441: Youtube Video/Playlist Downloader
* A script that allows the download of videos or playlist.

I would like to work on this script under the mentorship of GSSOC21.

## Details
* Addition of arguments that can:
    - Allows the user to download the video with any quality.
    - Allows the user to download the audio source only.
    - Download full playlists.

## Features
* Code will be commented so it can be easy to read the code flow, and for any furthur contributions to it.
* A documentation will be added before going along with the pull request.
* If possible I may add an executable version of the script. (.exe file)

### PR DESCRIPTION
**Pull request by XZANATOL**
# Description

Added Youtube Video/Playlist Downloader under the name of DownTube.

## Fixes #441

Replace #441 with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by antrikshmisri — APPROVED** [review]
Looks good to me. @kaustubhgupta @tamanna-verma @santushtisharma10 what do you say?

**Review by kaustubhgupta — APPROVED** [review]
Pretty dope implementation! I have tried this and failed most of the time but this time I learnt new techniques from this PR. Good Going Buddy 💯 👍🏼

**Review by santushtisharma10 — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯..Great Work @XZANATOL

**Comment by avinashkranjan** [comment]
@all-contributors please add @XZANATOL  for code and documentation

**Pull request merged**
