### PR TITLE
Feature/covid stats

### LINKED ISSUE #18: Facebook messenger bot to get COVID statistics
# Aim

- Build a Facebook messenger bot, that will display the current statistics of COVID-19 given a county or any Indian state or district

### PR DESCRIPTION
**Pull request by dsg1320**
# Description

This project uses an external API for getting the stats of COVID in Indian states

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — APPROVED** [review]
Great Job @dsg1320 💯 🥇

**Comment by dsg1320** [comment]
Ok thanku😊👍

**Comment by kaustubhgupta** [comment]
@antrikshmisri @santushtisharma10

**Review by antrikshmisri — APPROVED** [review]

**Review by santushtisharma10 — APPROVED** [review]
@dsg1320 💯

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
