### PR TITLE
Nse stocks GUI

### LINKED ISSUE #900: NSE stock market data GUI
# Aim

Web scrape stock market data (top 20 gainers/losers, most active equities etc ) 

# Details
display this scraped data in a GUI format where user can chose which market data analysis they want to see from a drop down menu

### PR DESCRIPTION
**Pull request by Ayushjain2205**
# Description

Script for NSE stocks data displaying GUI

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — COMMENTED** [review]
Can you use urlrequest to fetch the website as currently the selenium opens up the website, then closes it and then updates it in the app. This makes the process slower and sometimes hang the application.

**Comment by Ayushjain2205** [comment]
> Can you use urlrequest to fetch the website as currently the selenium opens up the website, then closes it and then updates it in the app. This makes the process slower and sometimes hang the application.

Sure I will do that

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  I have tried all ways of using urlrequest, used timeout along with it, tried requests_html and other things aswell.
But as this is a dynamic website I will have to use selenium along with chrome webdriver.

So I was thinking If I load all the data (of all categories) in one function itself instead of opening the webdriver in every function call.
That will improve the performance I fell. Please correct me if I am wrong

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta I have tried all ways of using urlrequest, used timeout along with it, tried requests_html and other things aswell.
> But as this is a dynamic website I will have to use selenium along with chrome webdriver.
> 
> So I was thinking If I load all the data (of all categories) in one function itself instead of opening the webdriver in every function call.
> That will improve the performance I fell. Please correct me if I am wrong

Okay so continue to use selenium and I have found the solution for the chrome opening tab: https://stackoverflow.com/questions/42476994/how-to-hide-chrome-driver-in-python

You can run the chrome driver as headless and no chrome UI will appear which made the process slow. Just add:
```python
chrome_options = Options()
chrome_options.headless = True
```

See if this works or not!

**Comment by Ayushjain2205** [comment]
@kaustubhgupta Its not working... The web scraper itself isnt working in headless mode while the same thing is working in normal mode

How do I proceed?

**Comment by kaustubhgupta** [comment]
@Ayushjain2205 what error you are facing?

**Comment by Ayushjain2205** [comment]
@kaustubhgupta  I am getting this error if I put the headless option without that it works fine

image

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta I am getting this error if I put the headless option without that it works fine
> 
> image

Hmm, then let's leave this idea, I am approving the PR

**Review by kaustubhgupta — APPROVED** [review]

**Review by Kushal997-das — APPROVED** [review]
LGTM 👍

**Review by antrikshmisri — APPROVED** [review]

**Review by santushtisharma10 — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]
LGTM

**Pull request merged**
