### PR TITLE
Snake_pygame.py

### LINKED ISSUE #2283: [Feat]: Add New Project
### Is your feature request related to a problem? Please describe.

It is a new project in python . 

### Describe the solution you'd like.

It is a classic game like "Snake" using Python's Pygame library

### Describe alternatives you've considered.

It provides a window, a controllable snake, food to eat, and basic collision detection

### Show us the magic with screenshots

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Shikhar9425**
# Description -
 It is a new project in python . It is a classic game like "Snake" using Python's Pygame library. It provides a window, a controllable snake, food to eat, and basic collision detection

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [x] AI/ML
- [x] Scrappers
- [ ] Social_Media
- [ ] PDF
- [x] Image_Processing
- [ ] Video_Processing
- [x] Games
- [ ] Networking
- [ ] OS_Utilities
- [x] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [x] Fun
- [x] Others

Title: \<write script title here\>

Folder: \<type the folder name that contains your script\>

Requirements: \<type the name of text file containing the required to install python packages, type None if no file required\>

Script: \<Enter the name of the ``.py`` file (The main entry point of the program)\>

Arguments: \<enter any arguments that the script needs but `-` separeted like: h-c-m\>

Contributor: \<Enter your Github handle/username without url\>

Description: \<Enter a one line description that describes your script. Also, explain the arguments usage here\>

### CODE REVIEW

**Comment by Shikhar9425** [comment]
@avinashkranjan please merge this pull request

**Comment by Shikhar9425** [comment]
@avinashkranjan Please merge this pull request

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Add a `README.md` file

**Comment by Shikhar9425** [comment]
@avinashkranjan I have done the required changes . please merge this pull request

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md

Please Follow this guidelines for the `README` file

**Comment by Shikhar9425** [comment]
@avinashkranjan I have done the following changes

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
