### PR TITLE
Data Visualization 

### PR DESCRIPTION
**Pull request by Ayush7614**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ ] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Ayush7614** [comment]
This pull is for #259 issue plss review it @avinashkranjan sir

**Review by atarax665 — COMMENTED** [review]
It would be better if you could use python notebook for this kind of programs where the output is in notebook itself. You can use jupyter notebook or google colab for this.

**Comment by atarax665** [comment]
Please demonstrate all the possible data visualization that can be done using matplotlib.

**Comment by Ayush7614** [comment]
> It would be better if you could use python notebook for this kind of programs where the output is in notebook itself. You can use jupyter notebook or google colab for this.

surely i use from next time

**Comment by Ayush7614** [comment]
> Please demonstrate all the possible data visualization that can be done using matplotlib.

sir plss explain what you say i doesn't understand

**Comment by Ayush7614** [comment]
> Please demonstrate all the possible data visualization that can be done using matplotlib.

Pls explain what you say

**Comment by atarax665** [comment]
> > Please demonstrate all the possible data visualization that can be done using matplotlib.
> 
> sir plss explain what you say i doesn't understand

There are other plots like pie plot, area plot, histogram etc please demonstrate them too.

**Comment by Ayush7614** [comment]
Now @avinashkranjan and @atarax665 sir plss review it

**Pull request merged**
