### PR TITLE
Gender age detector

### PR DESCRIPTION
**Pull request by codebuzzer01**
# Description

This is a gender-age detector to automatically detect the gender and age of the person(s)  present while camera is turned on.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [X] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [X] Documentation Update

## Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have created a helpful and easy to understand `README.md`
- [X] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [X] My changes generate no new warnings
- [X] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by santushtisharma10** [comment]
@codebuzzer01 you have copied your code from [here](https://github.com/smahesh29/Gender-and-Age-Detection).

**Comment by codebuzzer01** [comment]
No @santushtisharma10  it's not the same as above.  The user who will use the app of above code would not be able to provide the images of his/her own choice(i.e. the sample images are already being given in the cod, only  for which the above  code will work) whereas my code will prompt the camera of the device and depending on the person or persons present in it will detect the gender age of the person.

**Comment by antrikshmisri** [comment]
@santushtisharma10 Yup, its the same code.

**Comment by kaustubhgupta** [comment]
@codebuzzer01 The code is exactly the same. You have just removed the image argument from the video capture but why you haven't removed the argument parser when there is no need for it? Can you justify what is need for argument parser in your code? Secondly, I already told you that your files were deleted by me then why you are still modifying the files? It is because you didn't sync with the PA repo before making the branch and your master branch commits accompanied in this branch too which is causing this merge conflict. 

Due to these reasons, the PR and associated issue are closed.

**Pull request closed without merging**
