### PR TITLE
Maze Generation Visualizer

### LINKED ISSUE #1069: Maze Generation
# Aim

-To create the mazes, I used the backtracker algorithm, this algorithm utilizes a stack data structure and is a depth-first search algorithm.

# Details

- with the help of pygame and random module I will make maze generation 
- Visualiser for backtracking algorithm to solve the maze.

### PR DESCRIPTION
**Pull request by soumik2012**
# Description

I Have added the folder in Maze Generation Visualizer and dependency is the pygame module to run the application.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

Category:
- [x] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [x] Fun
- [ ] Others

Title: Maze Generation Visualizer

Folder: Maze-Generation-Visualizer

Requirements: pygame,random

Script: Maze-Generation-Visualiser.py

Arguments: N/A

Contributor: soumik2012

Description: Python scripts for generating random solvable mazes using the depth-first search and recursive backtracking algorithms. The code also implements a recursive backtracking pathfinding algorithm for solving the generated mazes.

### CODE REVIEW

**Comment by soumik2012** [comment]
@kaustubhgupta please check my PR

**Comment by soumik2012** [comment]
@kaustubhgupta please check my PR

**Comment by soumik2012** [comment]
@kaustubhgupta  please check my  PR

**Review by kaustubhgupta — COMMENTED** [review]
@santushtisharma10 can you check this script for plagiarism?

**Comment by santushtisharma10** [comment]
the whole code is copied from [here](https://github.com/Jack92829/Maze-Generation/blob/master/Visualisation/Maze-Generation-Visualiser.py). Just added a comment in first few lines of code

**Comment by kaustubhgupta** [comment]
Plagiarism not accepted

**Pull request closed without merging**
