### PR TITLE
Adding Contributors list

### LINKED ISSUE #290: Adding Contributors List to the Website
# Aim

- Since the Landing Page of the Website is Ready, Add the Contributors Sections and People who have contributed to the Repo

### PR DESCRIPTION
**Pull request by kagritu**
# Description

I have added the contributors list in the landing page

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

 [ ] Yes

## Type of change

_Please delete options that are not relevant._

- [ ] Documentation Update

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — APPROVED** [review]

**Comment by kaustubhgupta** [comment]
@antrikshmisri @santushtisharma10 reason for approval: https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/654#issuecomment-803272491

**Review by santushtisharma10 — APPROVED** [review]

**Comment by kaustubhgupta** [comment]
@antrikshmisri

**Review by antrikshmisri — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]

**Comment by avinashkranjan** [comment]
Resolve the conflicts @kagritu

**Comment by kagritu** [comment]
Okay

**Comment by kaustubhgupta** [comment]
@kagritu you haven't resolved the conflicts?

**Comment by kagritu** [comment]
Not yet, i am not understanding why i am getting this conflicts, can you help me out?

**Comment by kaustubhgupta** [comment]
Actually, the previous participant made some changes in the home.html file which hot merged and now they are conflicting with your changes. I would suggest take a look at the modified file (home.html), copy that and then make your changes.

**Comment by kagritu** [comment]
Okay

**Review by kaustubhgupta — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
