### PR TITLE
Qr code

### LINKED ISSUE #703: GUI QR code genrator system with python
my name is Jay Gohel.  Participate in GSSOC'21.

**Aim***
- This is GUI(Graphical User interface) based QR code generator system using python. 

**Description**
- in this app, I can make GUI using Tkinter. Genrate the qrcode usinf PyPi.  
- can you assign me this feature?

### PR DESCRIPTION
**Pull request by Goheljay**
# Description
@kaustubhgupta @antrikshmisri 
I have to complete my QR code generator project. also, I completed my "requirment.txt" file.
Old pull Request #760 

## Fixes #703 

Replace `#703` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

I can't be adding this updated file in old PR. that's why I made new PR.

### CODE REVIEW

**Review by kaustubhgupta — APPROVED** [review]
@Goheljay 💯

**Review by Kushal997-das — APPROVED** [review]
@Goheljay Great 💯

**Review by antrikshmisri — APPROVED** [review]

**Review by santushtisharma10 — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯

**Comment by Goheljay** [comment]
can you explain to me what is "LGTM.."?

**Comment by kaustubhgupta** [comment]
> can you explain to me what is "LGTM.."?
> 
> @avinashkranjan and thank you for merged my PR.

Looks good to me :)

**Pull request merged**
