### PR TITLE
Turtle Racing

### LINKED ISSUE #1098: Turtle Racing Game
# Aim

Hosting a race

# Details

The user will bet on a turtle to win and a race would be hosted to see who wins.

### PR DESCRIPTION
**Pull request by anumshka**
# Description

The user will bet on a turtle to win and a race would be hosted to see who wins.

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [x] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [x] Fun
- [x] Others

Title: Turtle Race

Folder: Turtle Race

Requirements: none

Script: TurtleRace.py

Arguments: None

Contributor: anumshka

Description: The user will bet on a turtle to win and a race would be hosted to see who wins.

### CODE REVIEW

**Review by kaustubhgupta — COMMENTED** [review]
image

display this result message in GUI and not in terminal

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
Bugs:
- The user input can be given as `yellow` but if the winner is `Yellow` color, it will still show loose the game. Possible solution: compare user input and winner color by converting the strings in lower case and then compare.
- The final result text just pops up on the screen and disappears. Make it permanent.

**Review by kaustubhgupta — APPROVED** [review]

**Review by kaustubhgupta — APPROVED** [review]
Cool 💯

**Review by santushtisharma10 — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]
LGTM..🚩

**Pull request merged**
