### PR TITLE
Pacman

### LINKED ISSUE #809: Pacman Game
# Aim

- To create a basic pacman game using python

# Details

- The script will have basic things like any other pacman game, a maze which has some aliens or monsters and obstacles. The objective of pacman is to come out of the maze successfully.

### PR DESCRIPTION
**Pull request by Amit366**
# Description

Added Pacman game

## Fixes #809

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ ] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by santushtisharma10** [comment]
@Amit366 your code is same as this [code](https://github.com/Prakhar-FF13/Pacman-game-using-Python/blob/master/pacman.py). Just few comments have been removed rest is exactly same.

**Comment by Amit366** [comment]
@santushtisharma10 there are many Pacman projects which have the same exact code. I thought since everyone is having the same code so we can't change anything.

**Comment by Amit366** [comment]
@santushtisharma10 I will make the changes.

**Comment by kaustubhgupta** [comment]
> @santushtisharma10 there are many Pacman projects which have the same exact code. I thought since everyone is having the same code so we can't change anything.

This is not a valid reason at all. If you are willing to contribute a unique code then we can give you some time.

**Comment by Amit366** [comment]
@kaustubhgupta I am closing this issue as I am not able to write an unique code and also don't want to get a plag-3 strike.

**Pull request closed without merging**
