### PR TITLE
Added code for Waterfall,Funnel,Ternary and Contour Plots

### LINKED ISSUE #917: Data Visualization
# Aim

- More types of visualizations like Financial Charts and Scientific Charts can be added

# Details

-  Scientific Charts like Contour Plots , Ternary Plots 
-  Financial Charts like Waterfall Chart , Funnel Chart

Contour Plot :
dv
Ternary Plot : 
dv2
Waterfall Chart:
dv3
Funnel Chart:
dv4

### PR DESCRIPTION
**Pull request by dsrao711**
# Description

- Added Code for Contour Plot , Ternary Plot , Funnel Chart and Waterfall Chart
- Created separate folder for each chart
- Updated README.md with images and author name 
contourplot
ternaryplot
WaterFall
FunnelChart

## Fixes #917 

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes  
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project 
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by dsrao711** [comment]
Completed issue #917 , Please have a look @kaustubhgupta

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
Make all the graphs dark theme by adding `fig.layout.template = 'plotly_dark'` in all the code files, update the screenshots too

**Comment by dsrao711** [comment]
@kaustubhgupta Added dark theme to all four plots and updated the screenshot . Please check

**Review by kaustubhgupta — APPROVED** [review]
Perfect 💯

**Review by antrikshmisri — APPROVED** [review]

**Review by Kushal997-das — APPROVED** [review]
LGTM 💯

**Review by santushtisharma10 — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
