### PR TITLE
Unzip a File Script

### PR DESCRIPTION
**Pull request by Priya96-sketch**
# AIM
## Unzipping a file

# Module Used:
```
zipfile module
```

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
@Priya96-sketch Have you created the issue of this script?

**Comment by kaustubhgupta** [comment]
@Priya96-sketch No response from your side

**Comment by Priya96-sketch** [comment]
> @Priya96-sketch Have you created the issue of this script?

Yes. I have created.

**Comment by Priya96-sketch** [comment]
Please assign it to me!

**Comment by kaustubhgupta** [comment]
@Priya96-sketch No issue has been assigned to you neither you made any issue

**Pull request closed without merging**
