### PR TITLE
Face mask detection added

### LINKED ISSUE #510: Mask or not
I would like to add a project for face mask detection using CNN. Here, I would use dataset which contains real life images of human faces.

### PR DESCRIPTION
**Pull request by sudipg4112001**
### Related issue
Fixes #510 

I have added the dataset, notebook and some sample images used for making the readme

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
@sudipg4112001 We need scripts not notebooks. I already informed you about this in this comment: https://github.com/avinashkranjan/Amazing-Python-Scripts/issues/510#issuecomment-797628317

You can refer to this PR for the right project structure: https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/556

**Comment by sudipg4112001** [comment]
I have made the required changes, Please do review.

**Comment by kaustubhgupta** [comment]
@sudipg4112001 Please make another PR, there was confusion from my end. Sorry for the confusion caused.

**Comment by sudipg4112001** [comment]
> @sudipg4112001 Please make another PR, there was confusion from my end. Sorry for the confusion caused.

I have made another PR #630

**Pull request closed without merging**
