### PR TITLE
Created contact us page for the website.

### PR DESCRIPTION
**Pull request by fatma-sia27**
Hey I had created a contact us page for the website "Amazing Python Scripts" , I had done frontend work. contactus2.html contains code of HTML and mycontactus.css contains code of CSS and images folder contains related images.
Please review it and if find any changes then please let me know , otherwise please merge it .
Thank you.

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
@fatma-sia27 Oops! You merged all the changes from the master branch! This PR will damage the whole project. I think, for now, you should add all the files via the web interface of GitHub. Just navigate to your forked repo, switch to gh-pages branch, and then add your files. You will again get the option to make a PR. Then raise that PR and make sure that you compare the right branches. Feel free to ping me again in case of any doubts!

**Comment by kaustubhgupta** [comment]
@fatma-sia27 updates?

**Comment by fatma-sia27** [comment]
gh pages
@kaustubhgupta ,I am doing it in right way? If yes, then please tell me what should I do next?

**Comment by kaustubhgupta** [comment]
@fatma-sia27 Start from the fresh. Delete all your local and remote branches. Delete your forked branch. Fork the repo again, switch to gh-pages branch in the Git web only. **Clone that branch only**. After that add your code changes, do all the git initials: 
- git add .
- git status
- git commit -m "Adding contact us files"
- git push origin <name-of-branch>

After this, go to github web version and make pull request comparing `avinashkranjan/Amazing-Python-Scripts` gh-branch with your's created branch. I hope you got the point

**Comment by kaustubhgupta** [comment]
@fatma-sia27 updates?

**Comment by kaustubhgupta** [comment]
@fatma-sia27 Today is the final day for this. After that I will have no choice but it close the issue.

**Comment by fatma-sia27** [comment]
> @fatma-sia27 Today is the final day for this. After that I will have no choice but it close the issue.

Hey sorry @kaustubhgupta , my exams is going on so I was busy in that . I will complete it by tomorrow. Is it ok?

**Comment by kaustubhgupta** [comment]
> > @fatma-sia27 Today is the final day for this. After that I will have no choice but it close the issue.
> 
> Hey sorry @kaustubhgupta , my exams is going on so I was busy in that . I will complete it by tomorrow. Is it ok?

Sure, Try to complete it by tomorrow

**Comment by kaustubhgupta** [comment]
@fatma-sia27 No more extensions, today is the FINAL day.

**Comment by fatma-sia27** [comment]
> @fatma-sia27 No more extensions, today is the FINAL day.

Yes I will do it today

**Comment by fatma-sia27** [comment]
Hey @kaustubhgupta I had created PR #924 , Please review it.
Thank you

**Pull request closed without merging**
