### PR TITLE
Palindrome Checker

### LINKED ISSUE #1534: [GSSOC '23]  To add Palindrome Checker Bot with GUI
# Aim

- The objective of the Palindrome Checker Bot is to allow users to easily determine whether a given word or phrase is a palindrome or not using "tkinter" and "custom tkinter" libraries of Python. 

# Details

- The Palindrome Checker Bot with GUI will include the following features:
 1. Graphical User Interface
 2. Input Field
 3. Check Button
 4. Real-time Feedback 

Thank you for your time and consideration. I look forward to your positive response.
@avinashkranjan

### PR DESCRIPTION
**Pull request by Abhishek-Rajput-81**
# Description
I have successfully added a Python script that checks whether a given word or phrase is a palindrome or not. It provides a graphical user interface (GUI) using the Tkinter library.

## **Output**
image

image

image

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [x] Others

Title: Palindrome Checker Script

Folder: Palindrome Checker

Script: main.py 

Contributor: Abhishek-Rajput-81

Description: Addition of Palindrome Checker

### CODE REVIEW

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan @Yashbhadiyadra

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan @avinashkranjan @avinashkranjan @avinashkranjan

**Review by avinashkranjan — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
