### PR TITLE
Hangman Game

### PR DESCRIPTION
**Pull request by Ayush7614**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ ] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Ayush7614** [comment]
@avinashkranjan plss review it this is pull for the issue no #245

**Comment by atarax665** [comment]
Please fill the PR template first.

**Review by atarax665 — COMMENTED** [review]
Remove all the files related to ```Guess the Number Game Program``` as they are irrelevant to this PR. You many raise a separate PR for it.

**Comment by Ayush7614** [comment]
@atarax665 bro i am deleted some files but some files are not deleted plsss tell me why plss help me bro

**Comment by atarax665** [comment]
> @atarax665 bro i am deleted some files but some files are not deleted plsss tell me why plss help me bro

You have deleted the branch from which you raised this PR. I will advice you to raise a new PR from a new branch with proper README, Screenshots and source code related to the issue #245

**Pull request closed without merging**
