### PR TITLE
ATM Program in python.

### LINKED ISSUE #442: ATM Program using Python
# Aim

- The main aim of this script is to get a clear understanding of conditionals. It also helps in logic building, while writing the code.

# Details

- Clean and easily understandable code.
- A Simple program but helps greatly in understanding conditionals.
- Helps to get a proper understanding on how to logically organize your program while dealing with multiple if/elif statements.
- It acts as a virtual ATM, asks for a pin. When the correct pin is entered it allows you to:
  1. Check your balance.
  2. Make withdrawals.
  3.  Deposit money.
  4. Return your credit card.
- It is a command line program.

### PR DESCRIPTION
**Pull request by PritKalariya**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #442

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ ] Yes

## Type of change

_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by santushtisharma10 — CHANGES_REQUESTED** [review]
@PritKalariya add a readme file to give brief description of your program

**Comment by PritKalariya** [comment]
Ohk!

**Comment by PritKalariya** [comment]
Done with the readme file. Please check.

**Review by kaustubhgupta — COMMENTED** [review]
Here are the bugs:
- When the script asks, "would you like to do something else (y/n)", and I select 'n', the program should exit instead of asking the PIN again because even if I entered the PIN again, it again asks for the pin and it's an infinite loop!
- If I choose option 4, "return card", it should reset the balance but it still showed me the last card balance.
- Set an upper limit in the "pay-in" option. (Maybe 50,000)
- Create the exit option as there is no way to exit.

**Comment by PritKalariya** [comment]
Ok! Will make the changes as soon as possible.

**Comment by kaustubhgupta** [comment]
@PritKalariya updates?

**Comment by PritKalariya** [comment]
Will complete it within 2 days for sure.

**Comment by kaustubhgupta** [comment]
> Will complete it within 2 days for sure.

Do this before tonight

**Comment by PritKalariya** [comment]
I'm sorry I was a bit low today so couldn't work.

**Comment by kaustubhgupta** [comment]
@PritKalariya I am assigning you the last 3 hours, after that this PR will be closed

**Comment by kaustubhgupta** [comment]
@PritKalariya What was the reason you closed the PR and issue of the same?

**Pull request closed without merging**
