### PR TITLE
Digital Clock

### PR DESCRIPTION
**Pull request by Dhanush2612**
Python program to display a digital clock in 12 hour format.
Fixes: #480

### CODE REVIEW

**Review by kaustubhgupta — APPROVED** [review]

**Comment by kaustubhgupta** [comment]
@antrikshmisri @santushtisharma10 Kindly review this, (approved from my side)

**Comment by antrikshmisri** [comment]
> @antrikshmisri @santushtisharma10 Kindly review this, (approved from my side)

@kaustubhgupta  Looks good to me.

**Review by antrikshmisri — APPROVED** [review]

**Review by santushtisharma10 — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯

**Comment by avinashkranjan** [comment]
@all-contributors please add @Dhanush2612  for code and documentation

**Comment by Dhanush2612** [comment]
Thank you

**Pull request merged**
