### PR TITLE
Update website

### LINKED ISSUE #1013: Updating Scripts contributors in Website, implementation of search bar and releasing the first draft!
## Problem
The website is almost ready to be showcased. One thing we still need to implement is script updation in the website. The current implementation is hard-coded HTML. The file [scripts.html](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/gh-pages/website/scripts.html) contains the scripts information but all has been done manually. Also, we need to implement a search bar where one can search for a script name. 

## Solution
The main branch contains a folder called master script and there you will find a file called datastore.json. Your task is to create the scripts to fetch that data onto the scripts.html and also implement the search functionality. For now, you can simply copy the JSON file to this branch, and later on, the GitHub action will automatically update this file. 

P.S: I have little knowledge about JS so anyone who takes this issue, kindly explain if this thing is possible or not

## More context:
- The contributors display on the home.html needs JS
- The website file needs to be shifted from the website folder to the root folder and the current index.html needs to be replaced with home.html

### PR DESCRIPTION
**Pull request by Ayushjain2205**
# Description

- Updating scripts on website to include dynamically from json file 
- Implementing search functionality

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
The search is working good but here is the thing, you have done changes on an older version of the website. Your branch gh-pages is not updated with the latest commits and that's why the banner image is old, the latest CSS changes are not shown plus there are no contributors on home.html.

I want you to pull the latest changes of gh-pages branch and then update your changes accordingly.

Also, when you will pull the latest changes of this branch, you will find that the home.html has contributors information hardcoded. Can you make JS script for that too and implement the search bar for that? I know it was not mentioned in the issue initially but I just realized that this thing can also be covered in this. I will update the issue and increase the level. Let me know your thoughts.

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta Sure will make all the changes and update the PR

Just an update: I have manually added the updated database to that branch, you can now pull the latest changes

**Comment by kaustubhgupta** [comment]
> > @kaustubhgupta Sure will make all the changes and update the PR
> 
> Just an update: I have manually added the updated database to that branch, you can now pull the latest changes

I have merged one last change to the gh-pages branch, now you can pull that change too and then work for your change

**Comment by Ayushjain2205** [comment]
> > > @kaustubhgupta Sure will make all the changes and update the PR
> > 
> > 
> > Just an update: I have manually added the updated database to that branch, you can now pull the latest changes
> 
> I have merged one last change to the gh-pages branch, now you can pull that change too and then work for your change

Sure will do that

**Pull request closed without merging**
