### PR TITLE
Added contact us files

### PR DESCRIPTION
**Pull request by fatma-sia27**
Hey I had added code of contact us page in order to make this website more beautiful and informative. Please review it .
thank you

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
@fatma-sia27 you are not understanding:

image

You are making the PR from the wrong branch. You need to place your files in this branch: https://github.com/fatma-sia27/Amazing-Python-Scripts/tree/gh-pages

and you are putting it here: https://github.com/fatma-sia27/Amazing-Python-Scripts/tree/master. Your this branch https://github.com/fatma-sia27/Amazing-Python-Scripts/tree/issue%23812 has all the commits from the master branch and not the gh-pages branch.

Kindly rectify this error today only.

**Comment by fatma-sia27** [comment]
> @fatma-sia27 you are not understanding:
> 
> image
> 
> You are making the PR from the wrong branch. You need to place your files in this branch: https://github.com/fatma-sia27/Amazing-Python-Scripts/tree/gh-pages
> 
> and you are putting it here: https://github.com/fatma-sia27/Amazing-Python-Scripts/tree/master. Your this branch https://github.com/fatma-sia27/Amazing-Python-Scripts/tree/issue%23812 has all the commits from the master branch and not the gh-pages branch.
> 
> Kindly rectify this error today only.

WhatsApp Image 2021-04-19 at 9 15 02 AM

@kaustubhgupta  , See I has tried to clone whatever you told but it is showing "no such repository found" . What should I do now?

**Comment by fatma-sia27** [comment]
@kaustubhgupta Please guide me.

**Comment by kaustubhgupta** [comment]
```bash
git clone -b gh-pages https://github.com/avinashkranjan/Amazing-Python-Scripts.git
```

**Comment by kaustubhgupta** [comment]
> ```shell
> git clone -b gh-pages https://github.com/avinashkranjan/Amazing-Python-Scripts.git
> ```

This is directly clone that branch, add your files accordingly and then try to make the PR 😃

**Comment by fatma-sia27** [comment]
> > ```shell
> > git clone -b gh-pages https://github.com/avinashkranjan/Amazing-Python-Scripts.git
> > ```
> 
> This will directly clone that branch, add your files accordingly and then try to make the PR 😃

Ok ok I will do it by today.

**Comment by fatma-sia27** [comment]
WhatsApp Image 2021-04-19 at 1 32 59 PM
@kaustubhgupta this is showing. Now??

**Comment by kaustubhgupta** [comment]
Oops I made the mistake will conversing the command. You need to clone your forked repo and not the PA's

```shell
git clone -b gh-pages https://github.com/fatma-sia27/Amazing-Python-Scripts.git
 ```

**Comment by fatma-sia27** [comment]
> Oops I made the mistake will conversing the command. You need to clone your forked repo and not the PA's
> 
> ```shell
> git clone -b gh-pages https://github.com/fatma-sia27/Amazing-Python-Scripts.git
> ```

Hey @kaustubhgupta , I had made PR#936 please review it .
Thank you

**Pull request closed without merging**
