### PR TITLE
Added 'Master Script' base JSON DB

### PR DESCRIPTION
**Pull request by XZANATOL**
# Description

First PR Considering `` Master Script `` project, which is a menu-driven script that creates a user-friendly interface that helps navigating in the repo. Added the JSON file DB

## Fixes issue #831 
(didn't correctly link it, to not automatically close the issue)

## Notes
1) Not all projects are added, some are yet still under discussion on how it should be implemented. - refer to this [comment](https://github.com/avinashkranjan/Amazing-Python-Scripts/issues/831#issuecomment-825877751) -
2) It will be appreciated that the next contributor updates the DB while doing his part as the repo adds new projects almost daily.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by XZANATOL** [comment]
@kaustubhgupta updates?

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta updates?

Hi, @XZANATOL I will review it in the afternoon as this is a big issue and I think that your script will make the pull request automation too. I will try to update you today

**Review by kaustubhgupta — APPROVED** [review]
Works Good! Now I think we can integrate the Pull request automation to add the projects directly to this JSON based on the data parameters defined in the Pull request template. I will ping PA that no new PR should be merged until we test out this feature.

**Comment by kaustubhgupta** [comment]
@santushtisharma10 @antrikshmisri this PR needs urgent attention and approval so that we can start working on the automation part

**Review by santushtisharma10 — APPROVED** [review]

**Review by antrikshmisri — APPROVED** [review]

**Comment by XZANATOL** [comment]
@kaustubhgupta So what is going to happen next is that we are going to import the script into a GitHub action which will get the required inputs of the database from an updated PR template. Am i correct?

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta So what is going to happen next is that we are going to import the script into a GitHub action which will get the required inputs of the database from an updated PR template. Am i correct?

Yes, you are correct. I am preparing some notes for this and I will share a pseudo implementation soon on the main issue. Then you can modify the script and then we will test it on our forked repos or maybe demo repositories. If it works well then I will instruct all the participants to fix their issue descriptions and merging them will be a real test for us. I hope it goes as expected.

**Review by Kushal997-das — APPROVED** [review]
LGTM 👍

**Comment by XZANATOL** [comment]
@kaustubhgupta this is getting really interesting. :D
OK, add on these that I've a demo repo where I use to test actions, we can use it for this goal.

**Pull request merged**
