### PR TITLE
i made screenshot to issue #1956 cause nobody did

### LINKED ISSUE #1956: [Script]: Automate_Screenshot
### Aim

 this script contain automate screenshot function using python by this simple code.

### Details

Automate Screenshot script to take Screenshot easily

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by bhavya1857**
# Description

This PR is in accordance to issue #1956 as it wasn't done by someone so I would like to solve this issue. This will allow the person to take a screenshot by setting a particular timer.

## Type of change

_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] I have added the project meta data in the PR template.
- [ ] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``. none

Category:

- [ ] Automation

Title: screenshot.py

Script: screenshot.py

Contributor: @bhavya1857

### CODE REVIEW

**Comment by bhavya1857** [comment]
You can have a look at this @avinashkranjan

**Comment by avinashkranjan** [comment]
@bhavya1857 Kindly Create a Directory and push the files in that directory and update the PR.

**Comment by bhavya1857** [comment]
i did it @avinashkranjan

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Put all the files in a Single Folder, In the Root Directory

**Pull request closed without merging**
