### PR TITLE
added a python script

### LINKED ISSUE #625: Life Expectancy Prediction
# Aim

- Life Expectancy Prediction using Machine Learning

# Details

- A typical Regression Machine Learning project leverages historical data to predict insights into the future. This problem statement is aimed at predicting Life Expectancy rate of a country given various features. Life expectancy is a statistical measure of the average time a human being is expected to live, Life expectancy depends on various factors: Regional variations, Economic Circumstances, Sex Differences, Mental Illnesses, Physical Illnesses, Education, Year of their birth and other demographic factors. This problem statement provides a way to predict average life expectancy of people living in a country when various factors such as year, GDP, education, alcohol intake of people in the country, expenditure on healthcare system and some specific disease related deaths that happened in the country are given.

### PR DESCRIPTION
**Pull request by guptadiksha307**
# Description

Added a folder called Life Expectancy Prediction.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ ] Yes

## Type of change

_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by santushtisharma10 — CHANGES_REQUESTED** [review]
@guptadiksha307 you have to add python file instead of notebook. Also , add a readme file giving a brief description, dependencies of your program

**Comment by kaustubhgupta** [comment]
@guptadiksha307 I already mentioned while assigning this issue to you that you need to structure your project as done in PR #556 or #638

**Comment by kaustubhgupta** [comment]
@guptadiksha307 updates on this?

**Comment by kaustubhgupta** [comment]
@guptadiksha307 final updates?

**Comment by guptadiksha307** [comment]
@kaustubhgupta I'm working on this. There was some issue with my laptop. Sorry for the delay.

**Pull request closed without merging**
