### PR TITLE
Add Spotify Downloader

### LINKED ISSUE #607: Spotify Downloader
# Aim
- What is the objective of the Script
- To download songs from Spotify

# Details
My script does the following
- Downloads music from Spotify as an MP3 file.
- Applies basic on metadata like track name, track number, album, genre and more.

### PR DESCRIPTION
**Pull request by muthuannamalai12**
# Description
Downloads music from Spotify as an MP3 file.
Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #607 (issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [x] No

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
The latest version of spotdl doesn't support any arguments. Kindly update the script according to v3. In v3, major improvements are made. https://github.com/spotDL/spotify-downloader

**Comment by kaustubhgupta** [comment]
@muthuannamalai12?

**Review by kaustubhgupta — COMMENTED** [review]
Why not copied the whole code from here: https://github.com/spotDL/spotify-downloader/blob/master/spotdl/__main__.py

You didn't run the script locally, just copied it from the link and done! Not acceptable at all

**Comment by kaustubhgupta** [comment]
@antrikshmisri @santushtisharma10 What to do in this case?

**Comment by antrikshmisri** [comment]
> @antrikshmisri @santushtisharma10 What to do in this case?

@kaustubhgupta This is getting really frustrating. I think we should deploy a github action for this , there are great free API's out there. We should talk to @avinashkranjan about this situation too.

**Comment by muthuannamalai12** [comment]
I should have not have done it. Sorry for it

**Comment by kaustubhgupta** [comment]
> > @antrikshmisri @santushtisharma10 What to do in this case?
> 
> @kaustubhgupta This is getting really frustrating. I think we should deploy a github action for this , there are great free API's out there. We should talk to @avinashkranjan about this situation too.

Yes, let me ping him

**Pull request closed without merging**
