### PR TITLE
[GSSOC'23] To add code for Measuring Internet Speed

### LINKED ISSUE #1481: [GSSOC'23] Request to add code for Measuring Internet Speed
# Aim

-  To measure the internet speed of a network connection using "Speedtest" library.

# Details
- The script will have the following features:
 1. Download Speed Measurement: The script will perform a download speed test to measure the rate at which data can be downloaded from the internet.

 2. Upload Speed Measurement: The script will also conduct an upload speed test to measure the rate at which data can be uploaded to the internet.

 3. Latency Measurement: The script will measure the latency or ping time, which represents the time it takes for a data packet to travel from the user's device to a server and back. This metric helps determine the responsiveness of the network connection.

### PR DESCRIPTION
**Pull request by Abhishek-Rajput-81**
Hii @avinashkranjan,  I've successfully added a feature that allows users to measure their Internet speed.
#1481 My Issue Number
# Description

 I've added a  feature for performing an internet speed test using the Speedtest library with GUI. It uses the Tkinter library to create the GUI window. The GUI provides a user-friendly and visually appealing way to measure download speed, upload speed, ping latency, and identify the best server for the speed test. Users can initiate the speed test by clicking a button, and the results are dynamically displayed in the interface. 
# Output
- Before Running the Speed Test 
image

- After Running the Speed Test
image

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.

## Project Metadata

Title: Add Code for Measuring Internet Speed

Folder: Internet-Speed-Test

Script: main.py

Contributor: [Abhishek-Rajput-81](https://github.com/Abhishek-Rajput-81)

Description: Adding Internet Speed Test GUI with Dynamic Results Display.

### CODE REVIEW

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan please review this

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan @avinashkranjan

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Remove empty `README` and add a `README` to this Folder.

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan I have added a README file 
please check now

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan @avinashkranjan

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan 
@avinashkranjan

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan @avinashkranjan

**Pull request merged**
