### PR TITLE
$connect 4 game

### LINKED ISSUE #614: Connect 4 game
**I have created a `connect-4`  game using `Python`.** 

### **_Game rules:_**

1. Get ready :)
2. 4 consecutive  balls should match of same colour `horizontally`   `vertically` `diagonally ( either of both)`
3. That's it now u r ready to play the game :)
@santushtisharma10 @tamanna-verma @antrikshmisri @kaustubhgupta please assign me the project.

I am sharing a glimpse of it. 
 > ### **Image-1**

image

> ### **Image-2**

image

### PR DESCRIPTION
**Pull request by syamala27**
# **_Description_**
This is a client-side game.
where 2 players can play one after the other.

### **_Game Rules:_**

- Get ready :)
- Four consecutive balls should match of the same color horizontally, vertically, or diagonally ( either or both) just like tic-tat-toe.
- That's it now u r ready to play the game :)

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #614

Replace `#614` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

> ### **_Image 1:_**

image

> ### **_Image2:_**

image

### CODE REVIEW

**Review by kaustubhgupta — APPROVED** [review]
Nice game 👍🏼

**Review by santushtisharma10 — APPROVED** [review]
LGTM 💯

**Review by antrikshmisri — APPROVED** [review]
Great Concept 💯

**Comment by syamala27** [comment]
Hello Mentors 
 Thank you so much for the feedback. This really means a lot to me :)

**Review by avinashkranjan — APPROVED** [review]
LGTM..🚩

**Pull request merged**
