### PR TITLE
Caesar cipher

### LINKED ISSUE #488: Caesar Cipher
# Aim

- Creating a script for caesar cipher

# Details

- Caesar's cipher, the shift cipher, is one of the simplest and most widely known encryption techniques. It is a type of substitution cipher in which each letter in the plaintext is replaced by a letter some fixed number of positions down the alphabet.

### PR DESCRIPTION
**Pull request by smriti1313**
# Description

Caesar cipher is added. Caesar cipher is a simple encrypting and decrypting words technique.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
@smriti1313 Files changed 92?

**Comment by smriti1313** [comment]
> @smriti1313 Files changed 92?

No i didn't change 92 files. Its just that when I began to work in branch, it showed that it was 100+ commits behind. So i thought of updating the branch with master and then squashed all the behinds into a single one. `1cea9be` commit has all the updates i did just to update the project with master.

**Review by antrikshmisri — CHANGES_REQUESTED** [review]
@smriti1313 revert this commit and make sure that your branch is even with [avinashkranjan:master](https://github.com/avinashkranjan/Amazing-Python-Scripts)

**Comment by smriti1313** [comment]
> 
> 
> @smriti1313 No worries , revert this commit and make sure that your branch is even with [avinashkranjan:master](https://github.com/avinashkranjan/Amazing-Python-Scripts)

I will be sending another PR then. Closing this for now.

**Pull request closed without merging**
