### PR TITLE
Flappy bird robin

### LINKED ISSUE #961: Flappy Bird Game
# Aim

- Flappy Bird Game 

# Details

- Flappy Bird game  in Python using PyGame Module

Assign me this issue under GSSoC 21

### PR DESCRIPTION
**Pull request by robin025**
# Description

Flappy Bird Game created using Pygame

## Fixes #(issue_no)

fixes #961 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [X] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [X] My changes generate no new warnings
- [X] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by kaustubhgupta — COMMENTED** [review]
Plagiarised: https://github.com/sourabhv/FlapPyBird

**Comment by robin025** [comment]
hello @kaustubhgupta  , sorry for the inconvenience, but I did not copy this code from another repo, this is the code that I learned from an udemy course, I really don't know if this source file has plagiarism, because as you have given a connection in the PR, it appears the, that source code consists of more than 430 lines of code as opposed to mine, which is about 250 lines.
I checked both source files and discovered that there are some methods that are similar but some that are completely different, for example, in that source code cycle method is used which I haven't used in mine source code
 I haven't even used the convert alpha method, and also haven't even used exception handling.

**Comment by robin025** [comment]
If you can provide me with some feedback on this source code, I will make improvements to eliminate plagiarism; however, using the Pygame module to construct this app would add similar methods, since there are no other methods that we can implement using Pygame to create flappyBird (as of my knowledge) ; that is to say, there might be some new methods to implement , but you will still find some similar methods to.

Regards

**Comment by kaustubhgupta** [comment]
It's not about the lines of code, you may have learned this in your course but the code is not unique because the way of implementation is the same. There can be many ways to implement the same task (maybe you could have used a class-based approach).

That's not happening alone with you. In past, all the PRs for this game have been marked plag. Therefore it is decided that we will not create an issue for this game.

**Pull request closed without merging**
