### PR TITLE
Add spotify downloader

### LINKED ISSUE #607: Spotify Downloader
# Aim
- What is the objective of the Script
- To download songs from Spotify

# Details
My script does the following
- Downloads music from Spotify as an MP3 file.
- Applies basic on metadata like track name, track number, album, genre and more.

### PR DESCRIPTION
**Pull request by Sibasish-Padhy**
file for spotify downloader

# script for spotify downloader

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #607 (issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by santushtisharma10** [comment]
@Sibasish-Padhy you copied your code from [here](https://github.com/SathyaBhat/spotify-dl/blob/master/spotify_dl/spotify.py). Only few parameter names have been changed, rest everything is same.

**Comment by kaustubhgupta** [comment]
@santushtisharma10 Actually @Sibasish-Padhy contacted me on discord that he needs help to refine the code that' why I told him to create a draft PR so that we can suggest to him how he can create different code other than the already available implementation. Therefore, it is not the case of plagiarism, this was a draft PR and not the final PR

**Review by kaustubhgupta — CHANGES_REQUESTED** [review]
- Why there are only functions and no main method to call these?
- As per the latest version of spotdl, you don't need this much specification and in v3, only the command-line argument of the song link will do the job. No need to define the tracks, albums, and playlist explicitly. Implement command-line based utility with the help of this documentation: 

https://github.com/spotDL/spotify-downloader#usage-instructions-for-v3

The code you have pushed in this PR is of no use

**Comment by santushtisharma10** [comment]
okay @kaustubhgupta

**Comment by Sibasish-Padhy** [comment]
Thank you sir for all your help but last night unfortunately I went through some laptop issues and hence my laptop's under repair right now I don't wanna waste much of your value worth time right now and so I request you all to unassign me this issue and assign it to someone else .I will take a couple of days and then I will be back to claim on some other issue.Thank you @kaustubhgupta sir for giving me a chance to work on this beginner friendly issue and sorry for letting you down.It was great fun to learn about this script .Please do give me the same opportunities ahead to contribute to your projects ahead in the 3 months journey.Thank you @kaustubhgupta sir

**Comment by kaustubhgupta** [comment]
@Sibasish-Padhy If you want, we can give you a week extra for this. Let me know your final decision

**Comment by Sibasish-Padhy** [comment]
Sir my laptop will be back till Tuesday and I can again start working on it from Wednesday so I think I will be able to draft A pr till Friday/next weekend .Thank you sir yes , I would certainly opt for it @kaustubhgupta sir.thank you

**Comment by kaustubhgupta** [comment]
@Sibasish-Padhy any updates?

**Comment by Sibasish-Padhy** [comment]
@kaustubhgupta sir will try to darft a PR till Sunday.. My laptop's still under repair.. If it wouldn't be possible then I would update you about it on saturday... And then you can reassign this issue. Thank you

**Comment by Sibasish-Padhy** [comment]
@kaustubhgupta sir you can reassign this issue to someone else.I will get my laptop back today evening.. So it wouldn't  be possible I think. Thank you for giving me the opportunity will work again on another issue soon

**Pull request closed without merging**
