### PR TITLE
#9 Added a README and minor improvements 

### LINKED ISSUE #9: Documentation: Adding Readme to the all the Scripts
# AIM

- Adding a Readme to all the scripts.

# Details

- There's no Instructions for the Scripts to explain how to works.
- So add a Readme for the Scripts which would help to overcome this problem.
- So, Add a Readme with SS to help understand how the script works.

### PR DESCRIPTION
**Pull request by mudit-mhjn**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #9 

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ -] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Documentation Update

## Checklist:

- [] My code follows the style guidelines(Clean Code) of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [] My changes generate no new warnings
- [] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by avinashkranjan — COMMENTED** [review]
Is this for SWOC

**Comment by mudit-mhjn** [comment]
Hey Avinash, 
No this is not for SWOC. I just found a minor improvement so decided to contribute, Very good repository though.

**Comment by avinashkranjan** [comment]
Oh, Thanks 
Thank You for Contributing..

**Review by avinashkranjan — APPROVED** [review]

**Comment by avinashkranjan** [comment]
@all-contributors please add @mudit-mhjn for code and documentation

**Pull request merged**
