### PR TITLE
Added csv to json script

### LINKED ISSUE #1659: CSV to JSON script [GSSoC'23]
# Aim

The aim of the script is to convert CSV files to JSON format. It provides a convenient way to transform data stored in CSV files into the JSON data structure.

# Details

The script has the following features:

CSV to JSON Conversion: The main functionality of the script is to convert a CSV file into JSON format. It reads the data from the CSV file, converts it into a JSON object, and writes it to a JSON file.

Input and Output Files: The script allows you to specify the input CSV file path and the output JSON file path. You can customize these file paths according to your needs.

CSV Parsing: The script uses the csv.DictReader class from the csv module to parse the CSV data. It treats the first row of the CSV file as column headers and maps each subsequent row to a dictionary where the keys are the column headers and the values are the corresponding row values.

JSON Formatting: The converted JSON data is formatted with an indentation of 4 spaces for improved readability. The json.dumps() function is used to convert the CSV data dictionary into a JSON string.

Error Handling: The script handles potential errors such as file not found or invalid file formats. It uses the with statement to automatically close the file handles, ensuring proper resource management.

### PR DESCRIPTION
**Pull request by sagnik-p**
# Description

Added a script that converts csv to json

csv : comma separated values
json: javascript object notation

This script reads the data from the given csv file and writes it to a json file.
This json can now be sent (just like api sends json objects)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

Modules required: json and csv , both are inbuilt

Category:
- [x] Networking
- [x] OS_Utilities
- [x] Others

Title: csv to json

Folder: Csv-To-Json-Converter

Requirements: none

Script: csv-to-json.py

Contributor: sagnik-p

Description: This script converts a csv file into a json file

### CODE REVIEW

**Comment by sagnik-p** [comment]
This issue was assigned to me and I have submitted the PR on time
Please verify and tell me if everything is alright
Please merge it as soon as possible

**Comment by sagnik-p** [comment]
@avinashkranjan please merge

**Comment by sagnik-p** [comment]
@avinashkranjan 
if there is any problem, tell me and I will fix it
Please merge asap
thanks

**Comment by sagnik-p** [comment]
What?why?
Plz merge or if there is any problem, tell me and I will rectify it

**Comment by sagnik-p** [comment]
There has been no response from your end
@avinashkranjan 


I have already submitted the PR on time
After this was assigned to me


I request you to merge this PR asap, I have been waiting for a long time

**Comment by avinashkranjan** [comment]
In the Issue #1659 It was already Assigned to someone else, and their PR is already merged.

**Pull request closed without merging**
