### PR TITLE
Number to Words conversion

### LINKED ISSUE #1523: [GSSOC'23] Number to Words convertor program
# Aim

- What is the objective of the Script
Convert Number to International system in words.
# Details

- What the features will your script have
Conversion of the number -> 

Input :-
123456 

Output :-
One Hundred Twenty Three Thousand Four Hundred Fifty Six.

Please Assign This program to me to contribute in GSSoC'23

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
# Description

**Creating a Python program which convert Number to Words Conversion.**

## Fixes #1523 

Resolve the issue number #1523 completely.
## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [x] Calculators
- [ ] Others

Title: Number to Words convertor

Folder: Number-To-Words

Requirements: None

Script: numToWords.py

Arguments: Only enter the digits

Contributor: [Avdhesh Varshney](https://github.com/Avdhesh-Varshney)

Description: Convertor progarm to convert digits into international system of the numbering.

Thanks !

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
Sir, please review my Pull request and merge into the main branch.
Thank you so much sir

**Comment by Avdhesh-Varshney** [comment]
Sir, please check my pull request and merge it into main branch please.

**Comment by Avdhesh-Varshney** [comment]
@avinashkranjan @Yashbhadiyadra Sir, please review my pull request and merge it into the main branch

**Comment by Avdhesh-Varshney** [comment]
Sirs @avinashkranjan @Yashbhadiyadra , please review my pull request and merge it into the main branch for successful contribution in the program GSSoC'23.
And sir please assign me the issues #1649 and #1662 to contribute in this repository.

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
