### PR TITLE
Added Temperature convertor GUI python script

### LINKED ISSUE #2046: [Script]: Temperature Convertor GUI
### Aim

I would like to create a Temperature convertor GUI application to inter-convert between them according to the user choices.

### Details

Units are
- Celsius 
- Kelvin
- Fahrenheit 
- Rankine 
- Réaumur 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Shikhar9425**
# Description-Added Temperature convertor GUI python script

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Type of change-Added Temperature convertor GUI python script

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update
- [X] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [x] AI/ML
- [x] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [x] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [x] Others

Title: \<write script title here\>

Folder: \<type the folder name that contains your script\>

Requirements: \<type the name of text file containing the required to install python packages, type None if no file required\>

Script: \<Enter the name of the ``.py`` file (The main entry point of the program)\>

Arguments: \<enter any arguments that the script needs but `-` separeted like: h-c-m\>

Contributor: \<Enter your Github handle/username without url\>

Description: \<Enter a one line description that describes your script. Also, explain the arguments usage here\>

### CODE REVIEW

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Convert this into python Script and add a `README` file

**Comment by Shikhar9425** [comment]
> Convert this into python Script and add a `README` file
[readme.md](https://github.com/avinashkranjan/Amazing-Python-Scripts/files/11967754/readme.md)

**Comment by Shikhar9425** [comment]
@avinashkranjan I have Converted this into python Script and added a README file also

**Comment by Shikhar9425** [comment]
@avinashkranjan  I have Converted this into python Script and added a README file also. 
Done the task

**Comment by Shikhar9425** [comment]
@avinashkranjan I have done requested changes

**Pull request merged**
