### PR TITLE
Adding the main script to fix issue #19

### PR DESCRIPTION
**Pull request by abirbhattacharya82**
# Description

Since I saw there was an issue which stated that they required a Calculator which has to made using Tkinter and GUI Toolkits, I decided to take up this topic

## Related Issues or Pull Requests

#19

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [X] Yes
- [ ] No

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Review by avinashkranjan — COMMENTED** [review]
@abirbhattacharya82 The calculator is very small. Kindly make the buttions a little bigger..and If you don't plan to use maximize function..Kindly disable it and update the script in the ReadMe Scripts Available table

**Review by abirbhattacharya82 — COMMENTED** [review]
Buttons Made Larger

**Review by abirbhattacharya82 — COMMENTED** [review]
* Buttons made Larger
* Maximize button is disabled

**Review by avinashkranjan — COMMENTED** [review]
Calculator is not able to take multiple equations 
Say, 20+30*60 .. Look in that.. Try exploring Eval function..
Make Clear Button Size Uniform with the the digits button size..It looks odd..

**Comment by abirbhattacharya82** [comment]
If I make the clear button bigger like the other button then it will be odd because I kept its height same as the height of the adjacent textbox. And a textbox height cannot be altered. However if you still want the size of the Clear button to be it can be done. And speaking of multiple equations I am working on it.

**Review by abirbhattacharya82 — COMMENTED** [review]
The Clear button is made comparitively Larger than before keeping it in parity with the height of the Text Box. Also supports Multiple calculation like a Standard Calculator.

**Review by avinashkranjan — APPROVED** [review]
Great...LGTM 💯

**Comment by avinashkranjan** [comment]
@all-contributors please add @abirbhattacharya82  for code

**Pull request merged**
