### PR TITLE
Covid-19 detection using Chest x-ray 

### PR DESCRIPTION
**Pull request by saiharsha-22**
@avinashkranjan I have solved issue #326

### CODE REVIEW

**Comment by avinashkranjan** [comment]
Change the PR Title..Link Correct Issue.. Use the default PR Template

**Comment by saiharsha-22** [comment]
@avinashkranjan changes the title now

**Comment by avinashkranjan** [comment]
> @avinashkranjan changed the title

Use the default PR Template

**Comment by saiharsha-22** [comment]
@avinashkranjan ok I will use default PR template. I will close the pull request and make a new one soon.

**Pull request closed without merging**
