### PR TITLE
discord bot

### LINKED ISSUE #55: Discord Bot
# Aim

- Code a Discord Bot

# Details

- Discord bot with moderation and information commands which is very easy to setup

### PR DESCRIPTION
**Pull request by vivax3794**
# Description

**Very** simple discord bot, should be easy to set up. includes 3 commands: ban. unban and kick. 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by vivax3794** [comment]
@avinashkranjan is this around the thing you wanted, or is it to simple?

**Comment by avinashkranjan** [comment]
@vivax3794 More 2-3 features would be nice...Like Greeting new members with custom message...Asking them to read the Rules pages, changing nickname... I think that would be enough for a simple bot..

**Review by avinashkranjan — APPROVED** [review]
LGTM.. 💯

**Comment by avinashkranjan** [comment]
@all-contributors please add @vivax3794 for code and documentation

**Pull request merged**
