### PR TITLE
[GSSOC'23] Added Readme file for Football-Player-Club-Info

### LINKED ISSUE #1516: [ GSSOC '23 ] Adding README.md file for Football-Player-Club-Info script.
# Aim

- To add a comprehensive README.md file which is essential for providing clear instructions and information about the script.

@avinashkranjan 
Thank you for considering this suggestion!

### PR DESCRIPTION
**Pull request by Abhishek-Rajput-81**
Hii @avinashkranjan  @Yashbhadiyadra, I've successfully added a README file for the Football-Player-Club-Info script.

# Description
This pull request adds a Readme file to provide essential information about the Football-Player-Club-Info project. The Readme file aims to guide users on how to set up the project, understand its purpose, and utilize its features effectively. It includes installation instructions, an overview of the project structure, and information about its dependencies and usage.

## Output
image

## Type of change

- [x] This change requires a documentation update
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)

## Project Metadata

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [x] Others

Title:  Added Readme file of Football Player Club Info

Folder: Football-Player-Club-Info

Script: README.md

Contributor: Abhishek-Rajput-81

### CODE REVIEW

**Comment by Abhishek-Rajput-81** [comment]
@Yashbhadiyadra @avinashkranjan

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan @Yashbhadiyadra

**Comment by Abhishek-Rajput-81** [comment]
@Yashbhadiyadra @avinashkranjan

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan @Yashbhadiyadra

**Comment by Abhishek-Rajput-81** [comment]
@avinashkranjan @Yashbhadiyadra

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
